



#include <stdlib.h>
#include "p_table.h"   // auto-generated by train.py, contains the trained Q-table
 #include "snd_game_over.h"
 #include "snd_wall.h"
 #include "snd_target.h"
 #include "snd_teleport.h"
 #include "teleport_frames.h"

// forward declarations
int  col_to_px(int col);
int  row_to_py(int row);
int  get_z_from_xy(int px, int py, char tilt);
struct TwoDPoint projectPoint(int x, int y, int z);
void plot_pixel(int x, int y, short int color);
void draw_circle(int cx, int cy, int r, short int color);
void fill_circle(int cx, int cy, int r, short int color);
void reset_round(int *cm, int *px, int *py);
void compute_dfs_path(int m, int ac, int ar);




// screen and tile constants
#define SCREEN_W  320
#define SCREEN_H  240
#define BLACK  0x0000
#define TILE 20
#define COLS 10
#define ROWS 10
#define NUM_MAPS 6
#define BALL_SIZE  8
#define SPEED 8

// offset to center the 200x200 maze on the 320x240 screen
#define MAP_OFFSET_X  ((SCREEN_W - COLS*TILE) / 2)   // = 60
#define MAP_OFFSET_Y  ((SCREEN_H - ROWS*TILE) / 2)   // = 20

// color definitions
#define WHITE  0xFFFF
#define RED  0xF800
#define GREEN 0x07E0
#define BLUE 0x001F
#define YELLOW 0xFFE0
#define CYAN 0x07FF
#define ORANGE 0xFD20

#define COL_BG 0x0000   // black background


#define COL_BG         0x0000   // black background
#define COL_WALL_OUTER 0x4208   // dark gray wall border
#define COL_WALL_CORE 0xFFFF   // white wall face
#define COL_WALL_SHINE 0xAD55   // light blue-gray wall highlight

// player ball
#define COL_PLAYER 0xF81F   // pink
#define COL_AGENT  0x001F   // blue

// target
#define COL_TARGET 0x07FF


// GAME MODES 
#define MODE_FREE   -1   // player only
#define MODE_RANDOM  0
#define MODE_DFS     1
#define MODE_RL      2

volatile int game_mode = MODE_FREE;

// DFS STORAGE 
#define MAX_PATH 200

int dfs_path[MAX_PATH];
int dfs_len = 0;
int dfs_index = 0;



// hardware interval timer at 0xFF202000
// runs at 100MHz so 100,000,000 ticks = 1 second
// we set it to fire every 1 second directly
#define TIMER_BASE       0xFF202000
#define TIMER_TICKS_1SEC 100000000   // 100MHz * 1 second

void timer_hw_init(void) {
    volatile int *timer = (int *) TIMER_BASE;
    *(timer + 2) = TIMER_TICKS_1SEC & 0xFFFF;         // low 16 bits of start value
    *(timer + 3) = (TIMER_TICKS_1SEC >> 16) & 0xFFFF; // high 16 bits
    *(timer + 1) = 0b0111;   // START + CONT + ITO (interrupt enable optional)
}

// returns 1 exactly once per second, 0 otherwise
int timer_hw_tick(void) {
    volatile int *timer = (int *) TIMER_BASE;
    if (*(timer + 0) & 0x1) {   // TO (timeout) flag set
        *(timer + 0) = 0;        // clear flag by writing any value
        return 1;
    }
    return 0;
}


// round timer globals — must be declared before draw_map, reset_round, and main
#define ROUND_TIME_SEC  30
int round_timer_sec  = ROUND_TIME_SEC;

// only needed if you kept the software timer fallback, remove if using hardware timer
int timer_tick_count = 0;

// position for timer display on screen — top right area
#define TIMER_X  280
#define TIMER_Y   20


// audio --------------------------
#define AUDIO_BASE 0xFF203040
volatile int *audio_ptr = (int *) AUDIO_BASE;

int  *clip_data = 0;
int   clip_len  = 0;
int   clip_pos  = -1;

void trigger_clip(int *data, int len) {
    clip_data = data;
    clip_len  = len;
    clip_pos  = 0;
}

void update_audio(void) {
    if (clip_pos < 0 || clip_pos >= clip_len) {
        clip_pos = -1;
        return;
    }
    int fifospace = *(audio_ptr + 1);
    int wslc = (fifospace >> 24) & 0xFF;
    if (wslc == 0) return;

    int sample = clip_data[clip_pos++];
    *(audio_ptr + 2) = sample;
    *(audio_ptr + 3) = sample;
}



// ── GPIO / I2C for accelerometer ──────────────────────────────────────────
typedef struct {
    volatile unsigned int DATA;
    volatile unsigned int DDR;
} GPIO_t;
#define GPIO_BASE     ((GPIO_t *)0xFF200060)
#define SCL_PIN       0
#define SDA_PIN       1
#define MPU_ADDR      0x68
#define REG_PWR_MGMT  0x6B
#define REG_ACCEL_X_H 0x3B
#define TILT_THRESHOLD 3000   // tune this — lower = more sensitive

// How many main-loop iterations to wait before accepting another accel move
// Prevents the ball from flying across the board on one tilt
#define ACCEL_MOVE_COOLDOWN 4000
static int accel_cooldown = 0;


void i2c_delay(void) { volatile int i; for (i = 0; i < 2000; i++); }
void sda_high(GPIO_t *g) { g->DDR  &= ~(1 << SDA_PIN); }
void sda_low (GPIO_t *g) { g->DATA &= ~(1 << SDA_PIN); g->DDR |= (1 << SDA_PIN); }
int  sda_read(GPIO_t *g) { g->DDR  &= ~(1 << SDA_PIN); i2c_delay(); return (g->DATA >> SDA_PIN) & 1; }
void scl_high(GPIO_t *g) { g->DDR  &= ~(1 << SCL_PIN); }
void scl_low (GPIO_t *g) { g->DATA &= ~(1 << SCL_PIN); g->DDR |= (1 << SCL_PIN); }

void i2c_start(GPIO_t *g) {
    sda_high(g); i2c_delay(); scl_high(g); i2c_delay();
    sda_low(g);  i2c_delay(); scl_low(g);  i2c_delay();
}
void i2c_stop(GPIO_t *g) {
    sda_low(g); i2c_delay(); scl_high(g); i2c_delay(); sda_high(g); i2c_delay();
}
int i2c_write_byte(GPIO_t *g, unsigned char byte) {
    for (int i = 7; i >= 0; i--) {
        if ((byte >> i) & 1) sda_high(g); else sda_low(g);
        i2c_delay(); scl_high(g); i2c_delay(); scl_low(g); i2c_delay();
    }
    sda_high(g); i2c_delay(); scl_high(g); i2c_delay();
    int nack = sda_read(g);
    scl_low(g); i2c_delay(); sda_high(g); i2c_delay();
    return nack;
}
unsigned char i2c_read_byte(GPIO_t *g, int send_ack) {
    unsigned char byte = 0;
    sda_high(g);
    for (int i = 7; i >= 0; i--) {
        i2c_delay(); scl_high(g); i2c_delay();
        if (sda_read(g)) byte |= (1 << i);
        scl_low(g);
    }
    if (send_ack) sda_low(g); else sda_high(g);
    i2c_delay(); scl_high(g); i2c_delay();
    scl_low(g); i2c_delay(); sda_high(g); i2c_delay();
    return byte;
}
void mpu_write_reg(GPIO_t *g, unsigned char reg, unsigned char val) {
    i2c_start(g);
    i2c_write_byte(g, MPU_ADDR << 1);
    i2c_write_byte(g, reg);
    i2c_write_byte(g, val);
    i2c_stop(g);
}
void mpu_read_regs(GPIO_t *g, unsigned char reg, unsigned char *buf, int len) {
    i2c_start(g);
    i2c_write_byte(g, MPU_ADDR << 1);
    i2c_write_byte(g, reg);
    i2c_start(g);
    i2c_write_byte(g, (MPU_ADDR << 1) | 1);
    for (int i = 0; i < len; i++)
        buf[i] = i2c_read_byte(g, i < len - 1);
    i2c_stop(g);
}





// 3D rendering constants
#define CAMERA_DISTANCE 135
#define HALF_BOX_WIDTH  18

// pixel buffer — 512 wide because DE1-SoC requires power-of-2 row stride
short int Buffer1[240][512];

// global game state
int target_col, target_row;
int agent_px, agent_py;

// pulse animation state — toggles each agent tick to animate the target ring
int pulse_frame = 0;
int playerScore = 0;
int computerScore = 0;
char prev_tilt = 'n';

// ────────────────────────────────────────────────────────────────────────────
// maze layouts  1=wall  0=open
// ───────────────────────────────────────────────
int maps[NUM_MAPS][ROWS][COLS] = {
{   // MAP 0: box with inner cross
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 1: zigzag corridors
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,0,1,0,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,0,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,0,1,0,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,1,1,0,1,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 2: ring with holes
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,0,0,0,0,0,1,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 3: chunks
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,0,1,0,1,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,1,1,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,1,1,0,1},
    {1,0,1,1,1,0,0,0,0,1},
    {1,0,0,0,0,0,1,1,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 4: symmetrical
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 5: pillars
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,0,0,1,0,0,1,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,1,0,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
};

// ────────────────────────────────────────────────────────────────────────────
// pixel drawing primitives
// ────────────────────────────────────────────────────────────────────────────
void plot_pixel(int x, int y, short int color) {
    if (x<0||x>319||y<0||y>239) return;
    Buffer1[y][x] = color;
}

void draw_rect(int x, int y, int w, int h, short int color) {
    for (int r = 0; r < h; r++)
        for (int c = 0; c < w; c++)
            plot_pixel(x+c, y+r, color);
}

void draw_circle(int cx, int cy, int r, short int color) {
    int x = 0, y = r, d = 1 - r;
    while (x <= y) {
        plot_pixel(cx+x,cy+y,color); plot_pixel(cx-x,cy+y,color);
        plot_pixel(cx+x,cy-y,color); plot_pixel(cx-x,cy-y,color);
        plot_pixel(cx+y,cy+x,color); plot_pixel(cx-y,cy+x,color);
        plot_pixel(cx+y,cy-x,color); plot_pixel(cx-y,cy-x,color);
        if (d < 0) d += 2*x+3;
        else { d += 2*(x-y)+5; y--; }
        x++;
    }
}

void fill_circle(int cx, int cy, int r, short int color) {
    for (int dy = -r; dy <= r; dy++)
        for (int dx = -r; dx <= r; dx++)
            if (dx*dx + dy*dy <= r*r)
                plot_pixel(cx+dx, cy+dy, color);
}

int abs(int x) { return x > 0 ? x : -x; }
void swap(int *x, int *y) { int t = *x; *x = *y; *y = t; }

void line(int x0, int y0, int x1, int y1, short color) {
    int steep = abs(y1-y0) > abs(x1-x0);
    if (steep)  { swap(&x0,&y0); swap(&x1,&y1); }
    if (x0>x1)  { swap(&x0,&x1); swap(&y0,&y1); }
    int dx = x1-x0, dy = abs(y1-y0);
    int err = -(dx/2), y = y0, ys = y0<y1 ? 1 : -1;
    for (int i = x0; i <= x1; i++) {
        if (steep) plot_pixel(y,i,color); else plot_pixel(i,y,color);
        err += dy;
        if (err > 0) { y += ys; err -= dx; }
    }
}

// scanline-fill a convex quad
// uses two slightly different fill modes to handle quads above/below screen center
void quad(int x0, int y0, int x1, int y1,
          int x2, int y2, int x3, int y3, short color) {
    int xs[4] = {x0,x1,x2,x3};
    int ys[4] = {y0,y1,y2,y3};

    int ymin = ys[0], ymax = ys[0];
    for (int i = 1; i < 4; i++) {
        if (ys[i] < ymin) ymin = ys[i];
        if (ys[i] > ymax) ymax = ys[i];
    }

    if (((x0>160)&&(y0>120)) || ((x0<160)&&(y0<120))) {
        // fill interior (exclusive top edge)
        for (int y = ymin+1; y < ymax; y++) {
            int intersections[4]; int count = 0;
            for (int i = 0; i < 4; i++) {
                int ax=xs[i], ay=ys[i], bx=xs[(i+1)%4], by=ys[(i+1)%4];
                if ((y>ay&&y<=by)||(y>by&&y<=ay)) {
                    intersections[count++] = ax + (y-ay)*(bx-ax)/(by-ay);
                }
            }
            for (int a = 0; a < count-1; a++)
                for (int b = a+1; b < count; b++)
                    if (intersections[a]>intersections[b]) {
                        int tmp=intersections[a];
                        intersections[a]=intersections[b];
                        intersections[b]=tmp;
                    }
            for (int a = 0; a < count-1; a += 2)
                for (int x = intersections[a]+1; x < intersections[a+1]; x++)
                    plot_pixel(x, y, color);
        }
    } else {
        // fill interior (inclusive edges)
        for (int y = ymin; y <= ymax; y++) {
            int intersections[4]; int count = 0;
            for (int i = 0; i < 4; i++) {
                int ax=xs[i], ay=ys[i], bx=xs[(i+1)%4], by=ys[(i+1)%4];
                if ((y>ay&&y<=by)||(y>by&&y<=ay)) {
                    intersections[count++] = ax + (y-ay)*(bx-ax)/(by-ay);
                }
            }
            for (int a = 0; a < count-1; a++)
                for (int b = a+1; b < count; b++)
                    if (intersections[a]>intersections[b]) {
                        int tmp=intersections[a];
                        intersections[a]=intersections[b];
                        intersections[b]=tmp;
                    }
            for (int a = 0; a < count-1; a += 2)
                for (int x = intersections[a]; x <= intersections[a+1]; x++)
                    plot_pixel(x, y, color);
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Pixel Art
// ────────────────────────────────────────────────────────────────────────────

void plot_picture(int* matrix, int rows, int cols, int xOffset, int yOffset, int pixelSize, short* colors) {
	short curr_col; 
	int draw_x;
	int draw_y;
	for(int x = 0; x < cols; x++){
        for(int y = 0; y < rows; y++){
			curr_col = colors[matrix[y * cols + x]];            
			for(int dy = 0; dy < pixelSize; dy++){
                for(int sx = 0; sx < pixelSize; sx++){
					
					draw_x = x * pixelSize + sx + xOffset;
					draw_y = y * pixelSize + dy + yOffset;
                    plot_pixel(draw_x, draw_y, curr_col);
                }
            }
        }
    }
}

#define SCORE_PX_SIZE 1
#define SCORE_X 10
#define SCORE_Y 10
	
int scoreboard[57][34] = {
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,1,1,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,1,1,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,1,1,1,0,0,0,1,1,0,1,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,1,1,1,1,0,1,1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,1,1,0,1,1,0,0,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0},
    {0,0,1,0,0,1,1,0,1,1,0,0,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0},
    {0,0,1,1,1,1,1,0,1,1,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1},
    {0,0,0,1,1,1,0,0,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1},
    {0,0,0,0,0,0,0,0,1,1,1,1,1,0,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,0,0},
    {1,1,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,0,0,0,1,1,0,0},
    {1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,0,0,1,1,1,1},
    {1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,0,0,0,1,1,0,1,1,0,0,0,1,1,1,1},
    {0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,1,0,0,1,1,0,0},
    {0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0},
    {0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1},
    {0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,2,2,2,2,2,0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0},
    {0,0,0,0,0,0,2,2,2,2,2,2,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1},
    {0,0,0,0,0,0,2,2,0,0,2,2,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1},
    {0,0,0,0,0,0,2,2,0,0,2,2,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1},
    {0,0,0,0,0,0,2,2,2,2,2,2,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,2,2,2,2,2,0,0,0,0,0,0,1,1,0,0,0,0,0,0,3,3,3,0,0,0,0,0,0},
    {0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,3,3,3,3,3,0,0,0,0,0},
    {0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,3,3,0,3,3,0,0,0,0,0},
    {1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,3,3,0,0,0,0,0,0,0,0},
    {1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,3,3,0,0,0,0,0,0,0,0},
    {1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,3,3,0,3,3,0,0,0,0,0},
    {0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,3,3,3,3,3,0,0,0,0,0},
    {0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,0,0,0,3,3,3,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,1,1,1,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1},
};


void plot_scoreboard() {
	short colors[] = {BLACK, WHITE, GREEN, RED};
	plot_picture(scoreboard, 57, 34, SCORE_X, SCORE_Y, SCORE_PX_SIZE, colors);
}


#define LOGO_PX_SIZE 1
#define LOGO_X 280
#define LOGO_Y 195
	
int logo[28][34] = {
	{0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0},
	{0,2,2,0,0,0,0,0,2,2,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,1,1,0,0,0,0,0,0},
	{0,2,2,2,0,0,0,2,2,2,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,1,1,0,0,0,0,0,0},
	{0,2,2,2,2,0,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0},
	{0,2,2,2,2,2,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0},
	{0,2,2,0,2,2,2,0,2,2,0,0,0,2,2,2,2,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0},
	{0,2,2,0,0,2,0,0,2,2,0,0,2,2,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,2,2,0,0,0,0,0,2,2,0,0,2,2,0,0,2,2,0,0,2,2,2,2,2,2,0,0,0,0,0,0,0,0},
	{0,2,2,0,0,0,0,0,2,2,0,0,2,2,0,0,2,2,0,0,2,2,2,2,2,2,0,0,0,0,0,0,0,0},
	{0,2,2,0,0,0,0,0,2,2,0,0,2,2,2,2,2,2,0,0,0,0,0,0,2,2,0,0,2,2,2,2,2,0},
	{0,2,2,0,0,0,0,0,2,2,0,0,2,2,2,2,2,2,0,0,0,0,0,2,2,2,0,0,2,2,2,2,2,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,2,2,0,0,0,0,2,2,2,0,0,0,2,2,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,2,2,0,0,0,2,2,2,0,0,0,0,2,2,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,2,2,0,0,2,2,2,0,0,0,0,0,2,2,2,2,2,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,2,2,0,0,2,2,0,0,0,0,0,0,2,2,2,2,2,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,0,0,2,2,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,0,0,2,2,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2},
};


void plot_logo() {
	short colors[] = {BLACK, WHITE, GREEN};
	plot_picture(logo, 28, 34, LOGO_X, LOGO_Y, LOGO_PX_SIZE, colors);
}


int num_art[10][10][6] ={
	{	{0,1,1,1,1,0},
		{1,1,1,1,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,1,1,1,1},
		{0,1,1,1,1},
	}, //0
	{	{0,0,0,0,1,1},
		{0,0,0,1,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
	}, //1
	{	{0,1,1,1,1,0},
		{1,1,1,1,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,1,1,1,1,1},
		{1,1,1,1,1,0},
		{1,1,0,0,0,0},
		{1,1,0,0,0,0},
		{1,1,1,1,1,1},
		{0,1,1,1,1},
	}, //2
	{	{0,1,1,1,1,0},
		{1,1,1,1,1,1},
		{1,1,0,0,1,1},
		{0,0,0,0,1,1},
		{0,1,1,1,1,1},
		{0,1,1,1,1,1},
		{0,0,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,1,1,1,1},
		{0,1,1,1,1},
	}, //3
	{	{1,1,0,0,0,0},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,1,1,1,1},
		{0,1,1,1,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
	}, //4
	{	{0,1,1,1,1,0},
		{1,1,1,1,1,1},
		{1,1,0,0,0,0},
		{1,1,0,0,0,0},
		{1,1,1,1,1,0},
		{0,1,1,1,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{1,1,1,1,1,1},
		{0,1,1,1,1},
	}, //5
	{	{0,1,1,1,1,0},
		{1,1,1,1,1,1},
		{1,1,0,0,0,1},
		{1,1,0,0,0,0},
		{1,1,1,1,1,0},
		{1,1,1,1,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,1,1,1,1},
		{0,1,1,1,1},
	}, //6
	{	{1,1,1,1,1,1},
		{1,1,1,1,1,1},
		{1,1,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
		{0,0,0,0,1,1},
	}, //7
	{	{0,1,1,1,1,0},
		{1,1,1,1,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{0,1,1,1,1,0},
		{1,1,1,1,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,1,1,1,1},
		{0,1,1,1,1},
	}, //8
	{	{0,1,1,1,1,0},
		{1,1,1,1,1,1},
		{1,1,0,0,1,1},
		{1,1,0,0,1,1},
		{1,1,1,1,1,1},
		{0,1,1,1,1,1},
		{0,0,0,0,1,1},
		{1,0,0,0,1,1},
		{1,1,1,1,1,1},
		{0,1,1,1,1,0},
	} //9
};

#define d1x 2 + SCORE_X
#define d1y 38 + SCORE_Y
#define d2x 9 + SCORE_X
#define d2y 40 + SCORE_Y
#define d3x 21 + SCORE_X
#define d3y 42 + SCORE_Y
#define d4x 28 + SCORE_X
#define d4y 44 + SCORE_Y

void plot_score(int player, int computer){
	short colors[] = {BLACK, WHITE};
	int d1 = (player%100)/10;
	int d2 = player%10;
	int d3 = (computer%100)/10;
	int d4 = computer%10;

	plot_picture(num_art[d1], 10, 6, d1x, d1y, SCORE_PX_SIZE , colors);
	plot_picture(num_art[d2], 10, 6, d2x, d2y, SCORE_PX_SIZE , colors);
	plot_picture(num_art[d3], 10, 6, d3x, d3y, SCORE_PX_SIZE , colors);
	plot_picture(num_art[d4], 10, 6, d4x, d4y, SCORE_PX_SIZE , colors);
}

// ────────────────────────────────────────────────────────────────────────────
// tile / pixel conversion helpers
// ────────────────────────────────────────────────────────────────────────────

#define BOX_OUTLINE_COLOR 0x9534
#define TILT_DAMPER 10
#define GLOBAL_Z -250

int px_to_col(int px) { return ((px + 260)/(3*TILE)); }
int py_to_row(int py) { return ((py + 270)/(3*TILE)); }

int col_to_px(int col) { return 3*col*TILE -260; }
int row_to_py(int row) { return 3*row*TILE -270; }

int get_z_from_xy(int px, int py, char tilt) {
	int htilt=0;
	int vtilt=0;
	
	if (tilt == 'l') htilt=1; //left
	if (tilt == 'r') htilt=-1; //right
	if (tilt == 'u') vtilt=1; //up
	if (tilt == 'd') vtilt=-1; //down
	if (tilt == 'n') {} //no button clicked
	return GLOBAL_Z + (((px*htilt)/TILT_DAMPER) + ((py*vtilt)/TILT_DAMPER));
}


// ────────────────────────────────────────────────────────────────────────────
// 3D perspective projection
// ────────────────────────────────────────────────────────────────────────────
struct TwoDPoint { int x; int y; };
struct BoxPoints {
    struct TwoDPoint ftl,ftr,fbl,fbr,btl,btr,bbl,bbr;
};

struct TwoDPoint projectPoint(int x, int y, int z) {
    struct TwoDPoint p;
    int d = CAMERA_DISTANCE;
    p.x = (-(x)*d)/(z-d)+160;
    p.y = (-(y)*d)/(z-d)+120;
    return p;
}

struct BoxPoints getBoxPoints(int x, int y, int z) {
    struct BoxPoints b; int w = HALF_BOX_WIDTH;
    b.ftl=projectPoint(x-w,y+w,z+w); b.ftr=projectPoint(x+w,y+w,z+w);
    b.fbl=projectPoint(x-w,y-w,z+w); b.fbr=projectPoint(x+w,y-w,z+w);
    b.btl=projectPoint(x-w,y+w,z-w); b.btr=projectPoint(x+w,y+w,z-w);
    b.bbl=projectPoint(x-w,y-w,z-w); b.bbr=projectPoint(x+w,y-w,z-w);
    return b;
}

// draw a 3D box with colored side faces and a white top face
void drawBox(int x, int y, int z, short color) {
    struct BoxPoints box = getBoxPoints(x,y,z);

    // colored side faces — only draw the face visible from camera position
    if (y<0)
        quad(box.btl.x,box.btl.y, box.btr.x,box.btr.y,
             box.ftr.x,box.ftr.y, box.ftl.x,box.ftl.y, RED);
    if (x>0)
        quad(box.fbl.x,box.fbl.y, box.bbl.x,box.bbl.y,
             box.btl.x,box.btl.y, box.ftl.x,box.ftl.y, GREEN);
    if (x<0)
        quad(box.ftr.x,box.ftr.y, box.btr.x,box.btr.y,
             box.bbr.x,box.bbr.y, box.fbr.x,box.fbr.y, BLUE);
    if (y>0)
        quad(box.fbl.x,box.fbl.y, box.fbr.x,box.fbr.y,
             box.bbr.x,box.bbr.y, box.bbl.x,box.bbl.y, ORANGE);

    // top/front face — always white
    quad(box.ftl.x,box.ftl.y, box.ftr.x,box.ftr.y,
         box.fbr.x,box.fbr.y, box.fbl.x,box.fbl.y, COL_WALL_CORE);

    // front face wireframe outline
    line(box.ftl.x,box.ftl.y, box.ftr.x,box.ftr.y, color);
    line(box.ftr.x,box.ftr.y, box.fbr.x,box.fbr.y, color);
    line(box.fbr.x,box.fbr.y, box.fbl.x,box.fbl.y, color);
    line(box.fbl.x,box.fbl.y, box.ftl.x,box.ftl.y, color);

    // back edges — only draw visible ones
    if(y<0) line(box.btl.x,box.btl.y, box.btr.x,box.btr.y, color);
    if(x<0) line(box.btr.x,box.btr.y, box.bbr.x,box.bbr.y, color);
    if(y>0) line(box.bbr.x,box.bbr.y, box.bbl.x,box.bbl.y, color);
    if(x>0) line(box.bbl.x,box.bbl.y, box.btl.x,box.btl.y, color);

    // connecting edges front-to-back
    if((y<0)||(x>0)) line(box.ftl.x,box.ftl.y, box.btl.x,box.btl.y, color);
    if((y<0)||(x<0)) line(box.ftr.x,box.ftr.y, box.btr.x,box.btr.y, color);
    if((y>0)||(x>0)) line(box.fbl.x,box.fbl.y, box.bbl.x,box.bbl.y, color);
    if((y>0)||(x<0)) line(box.fbr.x,box.fbr.y, box.bbr.x,box.bbr.y, color);
}

// draw one wall tile as a 3D box at the given tile position
	
void draw_wall_tile(int col, int row, char tilt) {
    int x = col_to_px(col);
    int y = row_to_py(row);
	int z = get_z_from_xy(x,y, tilt);
	
    drawBox(x, y, z, BOX_OUTLINE_COLOR);
}

void draw_timer(int seconds) {
    // erase old timer area first
    draw_rect(TIMER_X, TIMER_Y, 16, 12, BLACK);

    short colors[] = {BLACK, WHITE};
    int d1 = seconds / 10;   // tens digit
    int d2 = seconds % 10;   // units digit

    plot_picture(num_art[d1], 10, 6, TIMER_X,     TIMER_Y, 1, colors);
    plot_picture(num_art[d2], 10, 6, TIMER_X + 8, TIMER_Y, 1, colors);
}




// ────────────────────────────────────────────────────────────────────────────
// sprite drawing
// ────────────────────────────────────────────────────────────────────────────

// draw the player ball (PINK) or RL agent ball (BLUE)
// pass color==BLACK to erase (draws a black rectangle over the bounding box)
void draw_ball(int x, int y, short color, char tilt) {

    int z = get_z_from_xy(x, y, tilt);
    int cx = projectPoint(x, y, z).x;
    int cy = projectPoint(x, y, z).y;

    // ERASE (robust — no artifacts)
    if (color == BLACK) {
        int r = BALL_SIZE/2 + 2;
        for (int dy = -r; dy <= r; dy++)
            for (int dx = -r; dx <= r; dx++)
                plot_pixel(cx + dx, cy + dy, BLACK);
        return;
    }

    // main ball
    fill_circle(cx, cy, BALL_SIZE/2, color);

    // 3D highlight (top-left)
    fill_circle(cx - 2, cy - 2, BALL_SIZE/6, 0xFFFF);
}

// draw the pulsing target at tile (col, row)
// pulse_frame alternates the outer ring radius and color each agent tick,
// creating a ripple-outward animation without needing a separate timer
// draw the target at tile (col, row)
void draw_target(int col, int row, short color) {

    int x = col_to_px(col);
    int y = row_to_py(row);
    int z = get_z_from_xy(x, y, prev_tilt);

    int cx = projectPoint(x, y, z).x;
    int cy = projectPoint(x, y, z).y;

    // erase
    if (color == BLACK) {
        draw_rect(cx - TILE/2, cy - TILE/2, TILE, TILE, BLACK);
        return;
    }

    // solid turquoise fill
    fill_circle(cx, cy, TILE/2 - 6, COL_TARGET);

    // turquoise ring (same color, clean look)
    draw_circle(cx, cy, TILE/2 - 2, COL_TARGET);
}

// pick a random open tile for the target, avoiding the ball start tile (bc, br)
void spawn_target(int m, int bc, int br) {
    int col, row;
    do {
        col = 1 + rand() % (COLS-2);
        row = 1 + rand() % (ROWS-2);
    } while (maps[m][row][col] != 0 || (col==bc && row==br));
    target_col = col;
    target_row = row;
    
    draw_target(target_col, target_row, COL_TARGET);

    // values for dfs only at spawn
    if (game_mode == MODE_DFS) {
        int ac = px_to_col(agent_px);
        int ar = py_to_row(agent_py);
        compute_dfs_path(m, ac, ar);
    }
}




// Make the following a different file for spawn_teleport stuff
// ----------------------------------
// ── Warp holes ────────────────────────────────────────────────────────────
#define PORTAL_RADIUS  6
#define PORTAL_LIFETIME 300   // in phys_ticks (~3 seconds at tick>=500)

//for sprite drawing
int portal_frame = 0;
int portal_frame_timer = 0;
#define PORTAL_ANIM_SPEED 4   // ticks per frame, tune this to speed up/slow down

typedef struct {
    int col_a, row_a;   // entry hole
    int col_b, row_b;   // exit hole
    int active;
    int life;           // countdown to despawn
} Portal;

Portal portal = {0};
int portal_spawn_timer = 0;
#define PORTAL_SPAWN_INTERVAL 600  // ticks between spawns


void draw_portal(int col, int row, short color) {
    int x = col_to_px(col);
    int y = row_to_py(row);
    int z = get_z_from_xy(x, y, prev_tilt);
    int cx = projectPoint(x, y, z).x;
    int cy = projectPoint(x, y, z).y;

    if (color == BLACK) {
        // erase: black out the sprite area
        int x0 = cx - PORTAL_W / 2;
        int y0 = cy - PORTAL_H / 2;
        for (int dy = 0; dy < PORTAL_H; dy++)
            for (int dx = 0; dx < PORTAL_W; dx++)
                plot_pixel(x0 + dx, y0 + dy, BLACK);
        return;
    }

    // draw current animation frame
    unsigned short *frame = teleport_frames[portal_frame];
    int x0 = cx - PORTAL_W / 2;
    int y0 = cy - PORTAL_H / 2;
    for (int dy = 0; dy < PORTAL_H; dy++) {
        for (int dx = 0; dx < PORTAL_W; dx++) {
            unsigned short px_color = frame[dy * PORTAL_W + dx];
            if (px_color != 0x0000)   // skip transparent pixels
                plot_pixel(x0 + dx, y0 + dy, px_color);
        }
    }
}

void draw_portals(void) {
    if (!portal.active) return;
    draw_portal(portal.col_a, portal.row_a, 0x07FF);  // cyan
    draw_portal(portal.col_b, portal.row_b, 0x07FF);  // same color — they're a pair
}

void erase_portals(void) {
    if (!portal.active) return;
    draw_portal(portal.col_a, portal.row_a, BLACK);
    draw_portal(portal.col_b, portal.row_b, BLACK);
}

void spawn_portal(int m, int px, int py) {
    int pcol = px_to_col(px);
    int prow = py_to_row(py);
    int ca, ra, cb, rb;
    do {
        ca = 1 + rand() % (COLS - 2);
        ra = 1 + rand() % (ROWS - 2);
    } while (maps[m][ra][ca] != 0 || (ca == pcol && ra == prow));
    do {
        cb = 1 + rand() % (COLS - 2);
        rb = 1 + rand() % (ROWS - 2);
    } while (maps[m][rb][cb] != 0 || (cb == ca && rb == ra) || (cb == pcol && rb == prow));

    portal.col_a = ca; portal.row_a = ra;
    portal.col_b = cb; portal.row_b = rb;
    portal.active = 1;
    portal.life = PORTAL_LIFETIME;
    draw_portals();
}

// Returns 1 if ball center is on a portal tile, sets *dest_col / *dest_row
int check_portal(int px, int py, int *dest_col, int *dest_row) {
    if (!portal.active) return 0;

    // ball 3d bounds
    int pz = get_z_from_xy(px, py, prev_tilt);
    int cx = projectPoint(px, py, pz).x;
    int cy = projectPoint(px, py, pz).y;

    int r = BALL_SIZE / 2;
    int minBallX = cx - r;
    int minBallY = cy - r;
    int maxBallX = cx + r;
    int maxBallY = cy + r;

    // check portal A
    int ax = col_to_px(portal.col_a);
    int ay = row_to_py(portal.row_a);
    int az = get_z_from_xy(ax, ay, prev_tilt);
    int acx = projectPoint(ax, ay, az).x;
    int acy = projectPoint(ax, ay, az).y;
    int minAX = acx - r, minAY = acy - r;
    int maxAX = acx + r, maxAY = acy + r;

    if (maxBallX >= minAX && minBallX <= maxAX &&
        maxBallY >= minAY && minBallY <= maxAY) {
        trigger_clip(snd_teleport, snd_teleport_len);
        *dest_col = portal.col_b;
        *dest_row = portal.row_b;
        return 1;
    }

    // check portal B
    int bx = col_to_px(portal.col_b);
    int by = row_to_py(portal.row_b);
    int bz = get_z_from_xy(bx, by, prev_tilt);
    int bcx = projectPoint(bx, by, bz).x;
    int bcy = projectPoint(bx, by, bz).y;
    int minBX = bcx - r, minBY = bcy - r;
    int maxBX = bcx + r, maxBY = bcy + r;

    if (maxBallX >= minBX && minBallX <= maxBX &&
        maxBallY >= minBY && minBallY <= maxBY) {
        trigger_clip(snd_teleport, snd_teleport_len);
        *dest_col = portal.col_a;
        *dest_row = portal.row_a;
        return 1;
    }

    return 0;
}

//-------------------------






// Different game mode algorithms:
// 1. Random action: EASY LEVEL KEY0
int random_action(int m, int ac, int ar) {
    int actions[4] = {0,1,2,3};

    for (int i = 0; i < 4; i++) {
        int j = rand() % 4;
        int tmp = actions[i];
        actions[i] = actions[j];
        actions[j] = tmp;
    }

    for (int i = 0; i < 4; i++) {
        int a = actions[i];
        int nac = ac, nar = ar;

        if (a == 0) nar--;
        else if (a == 1) nar++;
        else if (a == 2) nac--;
        else if (a == 3) nac++;

        if (nac >= 0 && nac < COLS && nar >= 0 && nar < ROWS &&
            maps[m][nar][nac] == 0)
            return a;
    }

    return 0;
}


// 2. DFS: MEDIUM LEVEL KEY1:
int dfs_compute(int m, int sc, int sr, int tc, int tr, int *out) {
    int stack_c[MAX_PATH], stack_r[MAX_PATH];
    int stack_dir[MAX_PATH];

    int visited[ROWS][COLS] = {0};

    int top = 0;
    stack_c[0] = sc;
    stack_r[0] = sr;
    stack_dir[0] = 0;

    visited[sr][sc] = 1;

    while (top >= 0) {
        int c = stack_c[top];
        int r = stack_r[top];

        if (c == tc && r == tr) {
            for (int i = 1; i <= top; i++)
                out[i-1] = stack_dir[i];
            return top;
        }

        int found = 0;

        for (int a = 0; a < 4; a++) {
            int nc = c, nr = r;

            if (a==0) nr--;
            else if (a==1) nr++;
            else if (a==2) nc--;
            else if (a==3) nc++;

            if (nc>=0 && nc<COLS && nr>=0 && nr<ROWS &&
                !visited[nr][nc] && maps[m][nr][nc]==0) {

                top++;
                stack_c[top] = nc;
                stack_r[top] = nr;
                stack_dir[top] = a;

                visited[nr][nc] = 1;
                found = 1;
                break;
            }
        }

        if (!found) top--;
    }

    return 0;
}

void compute_dfs_path(int m, int ac, int ar) {
    dfs_len = dfs_compute(m, ac, ar, target_col, target_row, dfs_path);
    dfs_index = 0;
}

int dfs_next_action(int m, int ac, int ar) {
    if (dfs_index < dfs_len)
        return dfs_path[dfs_index++];
    return 0;
}

// Game mode switching
void set_mode(int new_mode, int *cm, int *px, int *py) {
    game_mode = new_mode;

    dfs_len = 0;
    dfs_index = 0;

    reset_round(cm, px, py);
}

// ────────────────────────────────────────────────────────────────────────────
// collision / detection
// ────────────────────────────────────────────────────────────────────────────

// check all 4 corners of the 8x8 ball bounding box for wall overlap
int hits_wall(int m, int px, int py) {
	
	//get the current tile the ball is in
	int col = px_to_col(px);
	int row = py_to_row(py);	
	
	//project ball to 3d
	int pz = get_z_from_xy(px,py, prev_tilt);
    int cx = projectPoint(px, py, pz).x;
    int cy = projectPoint(px, py, pz).y;
	
	//obtain 3d bounds
	int r = BALL_SIZE/2+1;
	int minBallX = cx-r;
	int minBallY = cy-r;
	int maxBallX = cx+r;
	int maxBallY = cy+r;
	
	//for each of the 9 surrounding tiles:
	for (int i = -1; i <=1; i++){
		for (int j = -1; j<=1; j++){
			
			//check if its an obstacle 
			if(maps[m][row+i][col+j]){
				
				//project to 3d
				int x = col_to_px(col+j);
				int y = row_to_py(row+i);
				int z = get_z_from_xy(x, y, prev_tilt);
				struct BoxPoints b = getBoxPoints(x,y,z);
				
				//obtain its bounding box
				int minX = b.ftl.x;
				int maxX = b.ftl.x;
				int minY = b.ftl.y;
				int maxY = b.ftl.y;
				
				struct TwoDPoint pts[8] = {b.ftl, b.ftr, b.fbl, b.fbr, b.btl, b.btr, b.bbl, b.bbr};

				for (int k = 1; k < 8; k++) {
    				if (pts[k].x < minX) minX = pts[k].x;
    				if (pts[k].x > maxX) maxX = pts[k].x;
    				if (pts[k].y < minY) minY = pts[k].y;
    				if (pts[k].y > maxY) maxY = pts[k].y;
				}

				if (prev_tilt == 'r' && j < 0) continue;
				if (prev_tilt == 'l' && j > 0) continue;
				if (prev_tilt == 'd' && i < 0) continue;
				if (prev_tilt == 'u' && i > 0) continue;
				
				//check for overlap	
				if (maxBallX >= minX && minBallX <= maxX &&
    				maxBallY >= minY && minBallY <= maxY) {return 1;}
				
				
							
			}
		}
	}
	
	return 0;
	
}

// check if ball center tile matches the target tile
int reached_target(int px, int py, int target_col, int target_row) {
	
    //ball 3d bounds
	int pz = get_z_from_xy(px,py, prev_tilt);
    int cx = projectPoint(px, py, pz).x;
    int cy = projectPoint(px, py, pz).y;

	int r = BALL_SIZE/2;
	int minBallX = cx-r;
	int minBallY = cy-r;
	int maxBallX = cx+r;
	int maxBallY = cy+r;
	
	//target 3d bounds
	int tx = col_to_px(target_col);
	int ty = row_to_py(target_row);
	int tz = get_z_from_xy(tx,ty,prev_tilt);
	
	int tcx = projectPoint(tx, ty, tz).x;
    int tcy = projectPoint(tx, ty, tz).y;
	
	int minTX = tcx-r;
	int minTY = tcy-r;
	int maxTX = tcx+r;
	int maxTY = tcy+r;
	
	//check overlap
	if (maxBallX >= minTX && minBallX <= maxTX &&
    				maxBallY >= minTY && minBallY <= maxTY) {return 1;}
	return 0;
}

// ────────────────────────────────────────────────────────────────────────────
// hardware I/O
// ────────────────────────────────────────────────────────────────────────────
void wait_for_vsync(void) {
    volatile int *ctrl = (int *)0xFF203020;
    *ctrl = 1;
    while ((*(ctrl+3) & 0x01) != 0);
}

volatile int *ps2 = (volatile int *)0xFF200100;
int ps2_read() {
    int val = *ps2;
    if (val & 0x8000) return val & 0xFF;
    return -1;
}

//  game over screen 
void go_delay(int amount) {
    volatile int d = 0;
    while (d < amount) {
        update_audio();
        d++;
    }
}

void draw_ring(int radius, short color) {
    int cx = 160, cy = 120;
    for (int y = 0; y < 240; y++)
        for (int x = 0; x < 320; x++) {
            int dx = x - cx, dy = y - cy;
            if (dx*dx + dy*dy <= radius*radius)
                Buffer1[y][x] = color;
        }
}

void draw_ring_band(int inner, int outer, short color) {
    int cx = 160, cy = 120;
    for (int y = 0; y < 240; y++)
        for (int x = 0; x < 320; x++) {
            int dx = x - cx, dy = y - cy;
            int d2 = dx*dx + dy*dy;
            if (d2 <= outer*outer && d2 >= inner*inner)
                Buffer1[y][x] = color;
        }
}

void draw_go_letter(int letter, int tx, int ty, short color) {
    if (letter == 0) {   // G
        draw_rect(tx+2, ty,    10, 2, color);
        draw_rect(tx,   ty+2,   2, 8, color);
        draw_rect(tx+2, ty+10, 10, 2, color);
        draw_rect(tx+8, ty+6,   4, 2, color);
        draw_rect(tx+10,ty+6,   2, 6, color);
    }
    else if (letter == 1) {   // A
        draw_rect(tx+4, ty,     4, 2, color);
        draw_rect(tx,   ty+2,   2, 10, color);
        draw_rect(tx+10,ty+2,   2, 10, color);
        draw_rect(tx,   ty+6,  12, 2, color);
    }
    else if (letter == 2) {   // M
        draw_rect(tx,   ty,     2, 12, color);
        draw_rect(tx+10,ty,     2, 12, color);
        draw_rect(tx+2, ty,     2,  4, color);
        draw_rect(tx+8, ty,     2,  4, color);
        draw_rect(tx+4, ty+2,   4,  2, color);
    }
    else if (letter == 3) {   // E
        draw_rect(tx,   ty,     2, 12, color);
        draw_rect(tx+2, ty,     8,  2, color);
        draw_rect(tx+2, ty+5,   6,  2, color);
        draw_rect(tx+2, ty+10,  8,  2, color);
    }
    else if (letter == 4) {   // O
        draw_rect(tx+2, ty,    8,  2, color);
        draw_rect(tx,   ty+2,  2,  8, color);
        draw_rect(tx+10,ty+2,  2,  8, color);
        draw_rect(tx+2, ty+10, 8,  2, color);
    }
    else if (letter == 5) {   // V
        draw_rect(tx,   ty,    2,  8, color);
        draw_rect(tx+10,ty,    2,  8, color);
        draw_rect(tx+2, ty+8,  2,  2, color);
        draw_rect(tx+8, ty+8,  2,  2, color);
        draw_rect(tx+4, ty+10, 4,  2, color);
    }
    else if (letter == 6) {   // E
        draw_rect(tx,   ty,     2, 12, color);
        draw_rect(tx+2, ty,     8,  2, color);
        draw_rect(tx+2, ty+5,   6,  2, color);
        draw_rect(tx+2, ty+10,  8,  2, color);
    }
    else if (letter == 7) {   // R
        draw_rect(tx,   ty,    2, 12, color);
        draw_rect(tx+2, ty,    8,  2, color);
        draw_rect(tx+10,ty+2,  2,  4, color);
        draw_rect(tx+2, ty+5,  8,  2, color);
        draw_rect(tx+4, ty+7,  2,  2, color);
        draw_rect(tx+6, ty+9,  4,  3, color);
    }
}

void show_game_over_screen(void) {

    // phase 1: expanding rings from center
    short ring_colors[6] = {0x07FF, 0xF81F, 0xFFE0, 0xFD20, 0xF800, 0xFFFF};
    int max_radius = 210;

    for (int r = 0; r <= max_radius; r += 3) {
        int band = (r * 6) / max_radius;
        if (band >= 6) band = 5;
        draw_ring(r, ring_colors[band]);
        go_delay(20000);
    }

    // fill fully black
    for (int y = 0; y < 240; y++)
        for (int x = 0; x < 320; x++)
            Buffer1[y][x] = 0x0000;
    go_delay(200000);

    // phase 4: letters appear one by one
    int letter_x[8] = {94, 112, 130, 148, 94, 112, 130, 148};
    int letter_y[8] = {85,  85,  85,  85, 105, 105, 105, 105};
    short letter_colors[8] = {
        0x07FF, 0xF81F, 0xFFE0, 0xFD20,   // G A M E
        0xF800, 0x07FF, 0xF81F, 0xFFE0    // O V E R
    };

    for (int i = 0; i < 8; i++) {
        draw_go_letter(i, letter_x[i], letter_y[i], letter_colors[i]);
        go_delay(40000);
    }

    // blinking press any key bar
    for (int blink = 0; blink < 6; blink++) {
        draw_rect(90, 165, 140, 6, 0xFFFF);
        go_delay(500000);
        draw_rect(90, 165, 140, 6, 0x0000);
        go_delay(500000);
    }
    draw_rect(90, 165, 140, 6, 0xFFFF);

    // wait for keypress
    volatile int *ps2_ptr = (volatile int *)0xFF200100;
    while (*ps2_ptr & 0x8000) { volatile int dummy = *ps2_ptr; (void)dummy; }
    while (!(*ps2_ptr & 0x8000));
}




// clear screen and redraw all wall tiles for map m
void draw_map(int m, char tilt) {
	
    for (int y = 0; y < SCREEN_H; y++)
        for (int x = 0; x < SCREEN_W; x++)
            Buffer1[y][x] = BLACK;
	
            
	plot_logo();
	plot_scoreboard();
	plot_score(playerScore, computerScore);
	draw_timer(round_timer_sec);

    for (int row = 0; row < ROWS; row++)
        for (int col = 0; col < COLS; col++)
            if (maps[m][row][col] == 1)
                draw_wall_tile(col, row, tilt);

    if (portal.active) draw_portals();

}


// ────────────────────────────────────────────────────────────────────────────
// round reset — pick new map, place both balls, spawn target
// ────────────────────────────────────────────────────────────────────────────

void reset_round(int *cm, int *px, int *py) {
    round_timer_sec  = ROUND_TIME_SEC; 
    timer_tick_count = 0; 

    *cm = rand() % NUM_MAPS;
    draw_map(*cm, 'n');
    *px = col_to_px(1);
    *py = row_to_py(1);
    agent_px = col_to_px(2);
    agent_py = row_to_py(1);
    
    //draw_ball(*px, *py, COL_PLAYER, prev_tilt);
    if (game_mode != MODE_FREE)
        draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);

    dfs_len = 0;
    dfs_index = 0;
    spawn_target(*cm, 1, 1);
	prev_tilt = 'u';

}

// ────────────────────────────────────────────────────────────────────────────
// main game loop
// ────────────────────────────────────────────────────────────────────────────

int justBounced = 0;
int cyclesSinceBounce;

int main(void) {
    volatile int *pixel_ctrl = (int *)0xFF203020;
    *(pixel_ctrl+1) = (int)&Buffer1;
    *pixel_ctrl = 1;
    while ((*(pixel_ctrl+3) & 0x01) != 0);
    *(pixel_ctrl+1) = (int)&Buffer1;

    int cm = 0; // Current map, start at first then be random
    draw_map(cm, 0);

    // player starts at tile (1,1)
    int px = col_to_px(1);
    int py = row_to_py(1);

	draw_ball(px, py, COL_PLAYER, prev_tilt);
	
    // RL agent starts at tile (2,1), one tile right of player
    agent_px = col_to_px(2);
    agent_py = row_to_py(1);
	
	 if (game_mode != MODE_FREE)
        draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);

    spawn_target(cm, 1, 1); // Spawns in a non taken space

    int e0 = 0, skip = 0; //for ps2 keyboard
    int agent_tick = 0; //how fast to update RL model (speed)
    int phys_tick  = 0;

	int ballSpeed = 0;

    timer_hw_init();

    // MPU6050 init
    GPIO_t *gpio = GPIO_BASE;
    gpio->DDR  &= ~((1 << SCL_PIN) | (1 << SDA_PIN));
    gpio->DATA &= ~((1 << SCL_PIN) | (1 << SDA_PIN));
    mpu_write_reg(gpio, REG_PWR_MGMT, 0x00);  // wake up
    mpu_write_reg(gpio, 0x1A, 0x03);           // low-pass filter


    while (1) {
        // RL AGENT MOVEMENT
        update_audio();  

        // TIMER 
        if (timer_hw_tick()) {
            round_timer_sec--;
            draw_timer(round_timer_sec);

            if (round_timer_sec <= 0) {
                trigger_clip(snd_game_over, snd_game_over_len);
                
                volatile int d = 0; while (d < 2000000) d++;
                show_game_over_screen();

                playerScore = 0;
                computerScore = 0;
                round_timer_sec = ROUND_TIME_SEC;
                ballSpeed   = 0;
                prev_tilt  = 'n';
                agent_tick = 0;
                reset_round(&cm, &px, &py);
            }
        }

        agent_tick++;
                
        if (agent_tick >= 60000) {
            agent_tick = 0;

            // ONLY move agent if a mode is active
            if (game_mode != MODE_FREE) {

                int ac = px_to_col(agent_px);
                int ar = py_to_row(agent_py);

                agent_px = col_to_px(ac);
                agent_py = row_to_py(ar);

                int action = 0;

                // MODE SWITCH
                if (game_mode == MODE_RANDOM) { //key 0
                    action = random_action(cm, ac, ar);
                }
                else if (game_mode == MODE_DFS) { //key 1
                    if (dfs_index >= dfs_len) {
                        compute_dfs_path(cm, ac, ar); // recompute if needed
                    }
                    action = dfs_next_action(cm, ac, ar);
                }
                else if (game_mode == MODE_RL) { //key 2
                    action = qt_best_action(ac, ar, target_col, target_row, cm); //use the table c array thing
                }

                int nac = ac, nar = ar; //update positions

                if (action == 0) nar--;
                else if (action == 1) nar++;
                else if (action == 2) nac--;
                else if (action == 3) nac++;

                // if in range draw
                if (nac >= 0 && nac < COLS && nar >= 0 && nar < ROWS && maps[cm][nar][nac] == 0) {

                    draw_ball(agent_px, agent_py, BLACK, prev_tilt);

                    agent_px = col_to_px(nac);
                    agent_py = row_to_py(nar);

                    draw_target(target_col, target_row, COL_TARGET);

                    if (game_mode != MODE_FREE)
                        draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);

                }

                if (reached_target(agent_px, agent_py, target_col, target_row)) {
                    computerScore++;
                    trigger_clip(snd_target, snd_target_len);  

                    reset_round(&cm, &px, &py);
                    dfs_index = dfs_len = 0; // reset DFS state
                    continue;
                }
            }
        }


        // ── PLAYER PHYSICS ────────────────────────────────────────────────
        phys_tick++;
		if(justBounced){
			cyclesSinceBounce++;
		}
		if(cyclesSinceBounce == 2){
			justBounced = 0;
			cyclesSinceBounce = 0;
		}
        if (phys_tick >= 8000) {
            phys_tick = 0;


            // advance portal animation
            if (portal.active) {
                portal_frame_timer++;
                if (portal_frame_timer >= PORTAL_ANIM_SPEED) {
                    portal_frame_timer = 0;
                    // erase old frame before drawing new one
                    erase_portals();
                    portal_frame = (portal_frame + 1) % PORTAL_FRAME_COUNT;
                    draw_portals();
                }
            }




            int nx = px, ny = py;

            if(ballSpeed<8)
                ballSpeed++;
                
            if(prev_tilt == 'u'){
                ny-=ballSpeed;
            } 
            else if(prev_tilt == 'd') {
                ny+=ballSpeed;
            } 
            else if(prev_tilt == 'r'){
                nx+=ballSpeed;
            } 
            else if(prev_tilt == 'l'){
                nx-=ballSpeed;
            }
                    
            draw_target(target_col, target_row, COL_TARGET); // redraw target
            
            if (game_mode != MODE_FREE)
                draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);
            
            draw_ball(px, py, COL_PLAYER, prev_tilt); // draw player
			
			
            if (!hits_wall(cm, nx, ny)) {   
                draw_ball(px, py, BLACK, prev_tilt);                          // erase player
                px = nx; 
                py = ny;

                draw_target(target_col, target_row, COL_TARGET); 	// redraw target

                if (game_mode != MODE_FREE)
                    draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);

                draw_ball(px, py, COL_PLAYER, prev_tilt);                   // draw player
            } 
			
            else {
                //trigger_sound(SOUND_WALL);
				if (!justBounced){
					ballSpeed *= -1;
					justBounced=1;
				}
            }

            // Portal spawn/despawn timer 
            portal_spawn_timer++;
            if (!portal.active && portal_spawn_timer >= PORTAL_SPAWN_INTERVAL) {
                portal_spawn_timer = 0;
                spawn_portal(cm, px, py);
            }
            if (portal.active) {
                portal.life--;
                if (portal.life <= 0) {
                    erase_portals();
                    portal.active = 0;
                    portal_spawn_timer = 0;
                }
            }

            // Portal teleport check (after moving ball) ────────────────────
            int dest_col, dest_row;
            if (check_portal(px, py, &dest_col, &dest_row)) {
                draw_ball(px, py, BLACK, prev_tilt);
                erase_portals();
                portal.active = 0;
                portal_spawn_timer = 0;
                // land the ball in the center of the destination tile
                px = col_to_px(dest_col);
                py = row_to_py(dest_row);
                ballSpeed = 0;   // brief pause after warp feels good
                draw_ball(px, py, COL_PLAYER, prev_tilt);
            }

            if (reached_target(px, py, target_col, target_row)) {
                playerScore++;
                trigger_clip(snd_target, snd_target_len);

                ballSpeed=0;
                reset_round(&cm, &px, &py);
                agent_tick = 0;
                prev_tilt = 'n';
                dfs_index = dfs_len = 0;

            } 


        }
			

        // ── ACCELEROMETER INPUT ───────────────────────────────────────────
        if (accel_cooldown > 0) {
            accel_cooldown--;
        } else {
            unsigned char abuf[6];
            mpu_read_regs(gpio, REG_ACCEL_X_H, abuf, 6);
            short ax = -(short)((abuf[0] << 8) | abuf[1]);
            short ay = -(short)((abuf[2] << 8) | abuf[3]);

            int abs_ax = ax < 0 ? -ax : ax;
            int abs_ay = ay < 0 ? -ay : ay;

            int nx = px, ny = py;
            char new_tilt = 'n';

            if (abs_ax > TILT_THRESHOLD || abs_ay > TILT_THRESHOLD) {
                if (abs_ax >= abs_ay) {
                    // X axis dominant
                    if (ax > 0) { new_tilt = 'l'; nx-=5; }
                    else        { new_tilt = 'r'; nx+=5; }
                } else {
                    // Y axis dominant
                    if (ay > 0) { new_tilt = 'd'; ny+=5; }
                    else        { new_tilt = 'u'; ny-=5; }
                }

                // Redraw map if tilt direction changed (for 3D effect)
                if (new_tilt != prev_tilt) {
                    prev_tilt = new_tilt;
                    draw_map(cm, prev_tilt);
                    draw_target(target_col, target_row, COL_TARGET);
                    if (game_mode != MODE_FREE)
                        draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);
                    draw_ball(px, py, COL_PLAYER, prev_tilt);
                }

                // Move ball one tile if not hitting a wall
                if (!hits_wall(cm, nx, ny)) {
                    draw_ball(px, py, BLACK, prev_tilt);
                    px = nx;
                    py = ny;
                    draw_target(target_col, target_row, COL_TARGET);
                    if (game_mode != MODE_FREE)
                        draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);
                    draw_ball(px, py, COL_PLAYER, prev_tilt);
                }

                accel_cooldown = ACCEL_MOVE_COOLDOWN;
            }
        }
        // ── END ACCELEROMETER INPUT ───────────────────────────────────────


		
        // PLAYER KEYBOARD INPUT 
        // PS2 protocol: 0xF0 = key release prefix, 0xE0 = extended key prefix
        int b;

        while ((b = ps2_read()) >= 0) {
            if (skip) { skip=0; e0=0; continue; }   // discard key-release scan code
            if (b == 0xF0) { skip=1; continue; }    // next byte is a key release
            if (b == 0xE0) { e0=1;   continue; }    // next byte is extended key			
			
			// MODE SWITCH KEYS (check first before player movement)
            if (!e0) {
                if (b == 0x45) {  // '0' — free/player only
                    game_mode = MODE_FREE;
                    dfs_index = dfs_len = 0;
                    draw_map(cm, prev_tilt);
                    draw_target(target_col, target_row, COL_TARGET);
                    draw_ball(px, py, COL_PLAYER, prev_tilt);
                }
                else if (b == 0x16) {  // '1' — random
                    game_mode = MODE_RANDOM;
                    dfs_index = dfs_len = 0;
                    draw_map(cm, prev_tilt);
                    draw_target(target_col, target_row, COL_TARGET);
                    if (game_mode != MODE_FREE)
                        draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);
                    draw_ball(px, py, COL_PLAYER, prev_tilt);
                }
                else if (b == 0x1E) {  // '2' — DFS
                    game_mode = MODE_DFS;
                    dfs_index = dfs_len = 0;
                    draw_map(cm, prev_tilt);
                    draw_target(target_col, target_row, COL_TARGET);
                    if (game_mode != MODE_FREE)
                        draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);
                    draw_ball(px, py, COL_PLAYER, prev_tilt);
                }
                else if (b == 0x26) {  // '3' — RL
                    game_mode = MODE_RL;
                    dfs_index = dfs_len = 0;
                    draw_map(cm, prev_tilt);
                    draw_target(target_col, target_row, COL_TARGET);
                    if (game_mode != MODE_FREE)
                        draw_ball(agent_px, agent_py, COL_AGENT, prev_tilt);
                    draw_ball(px, py, COL_PLAYER, prev_tilt);
                }
            }

            if (e0) {
                if (b==0x6B) { // left arrow
					
					if (prev_tilt != 'l') {
						prev_tilt = 'l';
						draw_map(cm, 'l');
						ballSpeed = 0;
					}
				} 
				
                else if (b==0x74) {// right arrow
					  
					if (prev_tilt != 'r') {
						prev_tilt = 'r';
						draw_map(cm, 'r');
						ballSpeed = 0; 
					}
				}
                else if (b==0x75) {// up arrow
		
					if (prev_tilt != 'u') {
						prev_tilt = 'u';
						draw_map(cm, 'u');
						ballSpeed = 0;
					}
				}
                else if (b==0x72) {// down arrow
					
					if (prev_tilt != 'd') {
						prev_tilt = 'd';
						draw_map(cm, 'd');
						ballSpeed = 0;
					}
				}
                e0 = 0;
            } 
            else {
                if (b==0x1D) { // W
					if (prev_tilt != 'u'){
						prev_tilt = 'u';
						draw_map(cm, 'u');
						ballSpeed = 0;
					}
				} 
                else if (b==0x1B) { // S
					if (prev_tilt != 'd'){
						prev_tilt = 'd';
						ballSpeed = 0;
						draw_map(cm, 'd');
					}
				}  
                else if (b==0x1C) {//A
					if (prev_tilt != 'l'){
						prev_tilt = 'l';
						draw_map(cm, 'l');
						ballSpeed=0;
					}
				}
                else if (b==0x23) {//D
					
					if (prev_tilt != 'r') {
						prev_tilt = 'r';
						draw_map(cm, 'r');
						ballSpeed=0;
					}
				} 
            }
        }
    }
    return 0;
}
