// ball.c  —  Polished Edition v2
//
// KEY FIXES vs v1:
//   • No flicker: proper double-buffering. We always draw into the BACK buffer
//     and flip with wait_for_vsync(). The full scene is composited off-screen
//     before it ever reaches the display — zero tearing, zero flash.
//
//   • True perspective tilt: the camera XY position slowly orbits the board
//     centre via integer sin/cos. Moving the camera (not the world) means the
//     vanishing point shifts — walls lean convincingly as if the board is
//     being physically tilted. Radius = TILT_R world units (kept subtle).
//
//   • Tilt advances once per agent move (not on a separate timer) so there is
//     no extra redraw cost and the motion stays perfectly in sync with gameplay.
//
//   • Target: 4-frame outward-ripple single blue ring over a solid cyan disc.
//   • Balls:  layered fill_circle with specular highlight, no ghost pixels.
//   • Walls:  quad_fill for every visible face, then dark outline on top.
//
// Requires: q_table.h  (auto-generated by train.py)
// Hardware: DE1-SoC  320x240 VGA, PS2 keyboard

#include <stdlib.h>
#include "q_table.h"

// ── constants ──────────────────────────────────────────────────────────────
#define SCREEN_W   320
#define SCREEN_H   240
#define TILE       20
#define COLS       10
#define ROWS       10
#define NUM_MAPS   6
#define BALL_SIZE  8
#define SPEED      4

#define MAP_OFFSET_X  60
#define MAP_OFFSET_Y  20

// ── colours (RGB565) ───────────────────────────────────────────────────────
#define BLACK      0x0000
#define WHITE      0xFFFF
#define RED        0xF800
#define ORANGE     0xFD20
#define CYAN       0x07FF

#define COL_WALL_TOP  0xFFFF
#define COL_WALL_L    0x6B4D
#define COL_WALL_R    0x2945
#define COL_WALL_BOT  0xFD20
#define COL_EDGE      0x18C3

// player pink
#define COL_P_OUT  0xF81F
#define COL_P_MID  0xFC3F
#define COL_P_IN   0xFFFF

// agent electric blue
#define COL_A_OUT  0x035F
#define COL_A_MID  0x07BF
#define COL_A_IN   0xAFFF

// target pulse
static const short PULSE_COL[4] = { 0x07FF, 0x043F, 0x001F, 0x000F };
static const int   PULSE_RAD[4] = { 6, 7, 8, 9 };

// ── double buffer ──────────────────────────────────────────────────────────
// DE1-SoC requires power-of-2 row stride (512 shorts)
short int Buffer1[240][512];
short int Buffer2[240][512];
// pointers swapped at each vsync flip
short int (*front_buf)[512];
short int (*back_buf )[512];

// ── camera / oscillation ───────────────────────────────────────────────────
// Camera orbits the scene centre at radius TILT_R in XY (camera Z = 0).
// Board sits at world Z = CAM_Z.  Moving the camera shifts the projection
// centre, making walls appear to lean — true perspective tilt.
#define TILT_R       18   // orbit radius world units — keep small for subtlety
#define CAM_Z      (-250) // board Z in world space
#define FOCAL       135   // perspective focal length (same as original)
#define HW           16   // half-width of each wall box world units

// 64-entry sin table, amplitude 32
static const int sin64[64] = {
     0, 3, 6, 9,12,15,18,21,24,26,28,30,31,32,32,32,
    32,32,31,30,28,26,24,21,18,15,12, 9, 6, 3, 0,-3,
    -6,-9,-12,-15,-18,-21,-24,-26,-28,-30,-31,-32,-32,-32,
    -32,-32,-31,-30,-28,-26,-24,-21,-18,-15,-12,-9,-6,-3
};
#define cos64(i) sin64[((i)+16)&63]

static int cam_ox = 0;
static int cam_oy = 0;
static int osc_phase = 0;

// ── game state ─────────────────────────────────────────────────────────────
int target_col, target_row;
int agent_px, agent_py;
int pulse_phase = 0;

// ── maps ───────────────────────────────────────────────────────────────────
int maps[NUM_MAPS][ROWS][COLS] = {
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,0,1,0,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,0,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,0,1,0,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,1,1,0,1,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,0,0,0,0,0,1,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,0,1,0,1,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,1,1,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,1,1,0,1},
    {1,0,1,1,1,0,0,0,0,1},
    {1,0,0,0,0,0,1,1,0,1},
    {1,0,1,1,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,0,0,1,0,0,1,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,1,0,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
};

// ── tile helpers ───────────────────────────────────────────────────────────
int px_to_col(int px){return (px+BALL_SIZE/2-MAP_OFFSET_X)/TILE;}
int py_to_row(int py){return (py+BALL_SIZE/2-MAP_OFFSET_Y)/TILE;}
int col_to_px(int c) {return MAP_OFFSET_X+c*TILE+(TILE-BALL_SIZE)/2;}
int row_to_py(int r) {return MAP_OFFSET_Y+r*TILE+(TILE-BALL_SIZE)/2;}

static int iabs(int x){return x>0?x:-x;}
static void iswap(int*a,int*b){int t=*a;*a=*b;*b=t;}

// ── draw into back buffer ──────────────────────────────────────────────────
static void plot(int x,int y,short c){
    if((unsigned)x<320u&&(unsigned)y<240u) back_buf[y][x]=c;
}
static void fill_rect(int x,int y,int w,int h,short c){
    for(int r=0;r<h;r++) for(int cc=0;cc<w;cc++) plot(x+cc,y+r,c);
}
static void fill_circle(int cx,int cy,int r,short c){
    for(int dy=-r;dy<=r;dy++)
        for(int dx=-r;dx<=r;dx++)
            if(dx*dx+dy*dy<=r*r) plot(cx+dx,cy+dy,c);
}
static void outline_circle(int cx,int cy,int r,short c){
    int x=0,y=r,d=1-r;
    while(x<=y){
        plot(cx+x,cy+y,c);plot(cx-x,cy+y,c);
        plot(cx+x,cy-y,c);plot(cx-x,cy-y,c);
        plot(cx+y,cy+x,c);plot(cx-y,cy+x,c);
        plot(cx+y,cy-x,c);plot(cx-y,cy-x,c);
        if(d<0)d+=2*x+3; else{d+=2*(x-y)+5;y--;}
        x++;
    }
}
static void draw_line(int x0,int y0,int x1,int y1,short c){
    int steep=iabs(y1-y0)>iabs(x1-x0);
    if(steep){iswap(&x0,&y0);iswap(&x1,&y1);}
    if(x0>x1){iswap(&x0,&x1);iswap(&y0,&y1);}
    int dx=x1-x0,dy=iabs(y1-y0);
    int err=-(dx/2),y=y0,ys=y0<y1?1:-1;
    for(int i=x0;i<=x1;i++){
        if(steep)plot(y,i,c);else plot(i,y,c);
        err+=dy; if(err>0){y+=ys;err-=dx;}
    }
}
static void quad_fill(int x0,int y0,int x1,int y1,
                      int x2,int y2,int x3,int y3,short c){
    int xs[4]={x0,x1,x2,x3},ys[4]={y0,y1,y2,y3};
    int ymin=ys[0],ymax=ys[0];
    for(int i=1;i<4;i++){if(ys[i]<ymin)ymin=ys[i];if(ys[i]>ymax)ymax=ys[i];}
    for(int y=ymin;y<=ymax;y++){
        int its[4],cnt=0;
        for(int i=0;i<4;i++){
            int ax=xs[i],ay=ys[i],bx=xs[(i+1)%4],by=ys[(i+1)%4];
            if((y>ay&&y<=by)||(y>by&&y<=ay))
                its[cnt++]=ax+(y-ay)*(bx-ax)/(by-ay);
        }
        for(int a=0;a<cnt-1;a++)
            for(int b=a+1;b<cnt;b++)
                if(its[a]>its[b]){int t=its[a];its[a]=its[b];its[b]=t;}
        for(int a=0;a<cnt-1;a+=2)
            for(int x=its[a];x<=its[a+1];x++) plot(x,y,c);
    }
}

// ── 3D projection via camera orbit ────────────────────────────────────────
typedef struct{int x,y;}P2;

// Camera is at (cam_ox, cam_oy, 0); board at z=CAM_Z (-250).
// Translate world point relative to camera, then standard pinhole.
static P2 project(int wx,int wy,int wz){
    int rx=wx-cam_ox, ry=wy-cam_oy;
    // rz = wz - 0 = wz  (camera z = 0)
    // screen_x = -rx * FOCAL / (FOCAL - rz) + 160
    // denominator: FOCAL - wz;  wz is negative so denom > FOCAL → correct
    int denom = FOCAL - wz;
    P2 p;
    p.x = (-rx*FOCAL)/denom + 160;
    p.y = (-ry*FOCAL)/denom + 120;
    return p;
}

typedef struct{P2 ftl,ftr,fbl,fbr,btl,btr,bbl,bbr;}Box;

static Box get_box(int wx,int wy,int wz){
    Box b;
    b.ftl=project(wx-HW,wy+HW,wz+HW); b.ftr=project(wx+HW,wy+HW,wz+HW);
    b.fbl=project(wx-HW,wy-HW,wz+HW); b.fbr=project(wx+HW,wy-HW,wz+HW);
    b.btl=project(wx-HW,wy+HW,wz-HW); b.btr=project(wx+HW,wy+HW,wz-HW);
    b.bbl=project(wx-HW,wy-HW,wz-HW); b.bbr=project(wx+HW,wy-HW,wz-HW);
    return b;
}

static void draw_wall_tile(int col,int row){
    int wx=col*3*TILE-260;
    int wy=row*3*TILE-270;
    Box b=get_box(wx,wy,CAM_Z);

    // filled faces first so outlines overdraw cleanly
    quad_fill(b.ftl.x,b.ftl.y,b.ftr.x,b.ftr.y,
              b.fbr.x,b.fbr.y,b.fbl.x,b.fbl.y, COL_WALL_TOP);
    if(wy<0)
        quad_fill(b.btl.x,b.btl.y,b.btr.x,b.btr.y,
                  b.ftr.x,b.ftr.y,b.ftl.x,b.ftl.y, RED);
    if(wx>0)
        quad_fill(b.fbl.x,b.fbl.y,b.bbl.x,b.bbl.y,
                  b.btl.x,b.btl.y,b.ftl.x,b.ftl.y, COL_WALL_L);
    if(wx<0)
        quad_fill(b.ftr.x,b.ftr.y,b.btr.x,b.btr.y,
                  b.bbr.x,b.bbr.y,b.fbr.x,b.fbr.y, COL_WALL_R);
    if(wy>0)
        quad_fill(b.fbl.x,b.fbl.y,b.fbr.x,b.fbr.y,
                  b.bbr.x,b.bbr.y,b.bbl.x,b.bbl.y, COL_WALL_BOT);

    short e=COL_EDGE;
    draw_line(b.ftl.x,b.ftl.y,b.ftr.x,b.ftr.y,e);
    draw_line(b.ftr.x,b.ftr.y,b.fbr.x,b.fbr.y,e);
    draw_line(b.fbr.x,b.fbr.y,b.fbl.x,b.fbl.y,e);
    draw_line(b.fbl.x,b.fbl.y,b.ftl.x,b.ftl.y,e);
    if(wy<0)draw_line(b.btl.x,b.btl.y,b.btr.x,b.btr.y,e);
    if(wx<0)draw_line(b.btr.x,b.btr.y,b.bbr.x,b.bbr.y,e);
    if(wy>0)draw_line(b.bbr.x,b.bbr.y,b.bbl.x,b.bbl.y,e);
    if(wx>0)draw_line(b.bbl.x,b.bbl.y,b.btl.x,b.btl.y,e);
    if((wy<0)||(wx>0))draw_line(b.ftl.x,b.ftl.y,b.btl.x,b.btl.y,e);
    if((wy<0)||(wx<0))draw_line(b.ftr.x,b.ftr.y,b.btr.x,b.btr.y,e);
    if((wy>0)||(wx>0))draw_line(b.fbl.x,b.fbl.y,b.bbl.x,b.bbl.y,e);
    if((wy>0)||(wx<0))draw_line(b.fbr.x,b.fbr.y,b.bbr.x,b.bbr.y,e);
}

// ── target ────────────────────────────────────────────────────────────────
static void draw_target(void){
    int cx=MAP_OFFSET_X+target_col*TILE+TILE/2;
    int cy=MAP_OFFSET_Y+target_row*TILE+TILE/2;
    fill_circle(cx,cy,4,CYAN);
    outline_circle(cx,cy,5,0x035F);
    outline_circle(cx,cy,PULSE_RAD[pulse_phase],PULSE_COL[pulse_phase]);
    plot(cx,  cy,  WHITE); plot(cx+1,cy,  WHITE);
    plot(cx,  cy+1,WHITE); plot(cx+1,cy+1,WHITE);
}

// ── balls ─────────────────────────────────────────────────────────────────
static void draw_ball(int x,int y,int is_agent){
    int cx=x+BALL_SIZE/2, cy=y+BALL_SIZE/2;
    if(is_agent){
        fill_circle(cx,cy,BALL_SIZE/2,   COL_A_OUT);
        fill_circle(cx,cy,BALL_SIZE/2-2, COL_A_MID);
        fill_circle(cx,cy,BALL_SIZE/2-3, COL_A_IN);
    } else {
        fill_circle(cx,cy,BALL_SIZE/2,   COL_P_OUT);
        fill_circle(cx,cy,BALL_SIZE/2-2, COL_P_MID);
        fill_circle(cx,cy,BALL_SIZE/2-3, COL_P_IN);
    }
    plot(cx-1,cy-2,WHITE); plot(cx,cy-2,WHITE); plot(cx-1,cy-1,WHITE);
}

// ── full composite into back buffer ───────────────────────────────────────
static void redraw_all(int m,int px,int py){
    // clear
    for(int y=0;y<240;y++)
        for(int x=0;x<320;x++)
            back_buf[y][x]=BLACK;
    // walls
    for(int r=0;r<ROWS;r++)
        for(int c=0;c<COLS;c++)
            if(maps[m][r][c]==1)
                draw_wall_tile(c,r);
    // sprites
    draw_target();
    draw_ball(agent_px,agent_py,1);
    draw_ball(px,py,0);
}

// ── vsync flip ─────────────────────────────────────────────────────────────
// Tells the hardware to start displaying what is currently in back_buf,
// waits for vsync, then swaps pointers so back_buf points to the old front.
static void flip(void){
    volatile int *ctrl=(int*)0xFF203020;
    // write address of what we just drew (back_buf) as the new front
    *(ctrl+1)=(int)back_buf;
    *ctrl=1;                          // trigger swap request
    while((*(ctrl+3)&1)!=0);         // wait for hardware to latch
    // swap CPU-side pointers
    short int (*tmp)[512]=front_buf;
    front_buf=back_buf;
    back_buf=tmp;
    // point register at the new back buffer so HW knows where we will write next
    *(ctrl+1)=(int)back_buf;
}

// ── hardware ──────────────────────────────────────────────────────────────
volatile int *ps2=(volatile int*)0xFF200100;
static int ps2_read(void){int v=*ps2;if(v&0x8000)return v&0xFF;return -1;}

// ── collision ──────────────────────────────────────────────────────────────
static int hits_wall(int m,int bx,int by){
    int pts[4][2]={{bx,by},{bx+BALL_SIZE-1,by},
                   {bx,by+BALL_SIZE-1},{bx+BALL_SIZE-1,by+BALL_SIZE-1}};
    for(int i=0;i<4;i++){
        int c=(pts[i][0]-MAP_OFFSET_X)/TILE;
        int r=(pts[i][1]-MAP_OFFSET_Y)/TILE;
        if(c<0||c>=COLS||r<0||r>=ROWS)return 1;
        if(maps[m][r][c]==1)return 1;
    }
    return 0;
}
static int reached_target(int bx,int by){
    int bc=(bx+BALL_SIZE/2-MAP_OFFSET_X)/TILE;
    int br=(by+BALL_SIZE/2-MAP_OFFSET_Y)/TILE;
    return(bc==target_col&&br==target_row);
}

// ── spawn ──────────────────────────────────────────────────────────────────
static void spawn_target(int m,int bc,int br){
    int col,row;
    do{col=1+rand()%(COLS-2);row=1+rand()%(ROWS-2);}
    while(maps[m][row][col]!=0||(col==bc&&row==br));
    target_col=col; target_row=row;
}
static void reset_round(int *cm,int *px,int *py){
    *cm=rand()%NUM_MAPS;
    *px=col_to_px(1); *py=row_to_py(1);
    agent_px=col_to_px(2); agent_py=row_to_py(1);
    pulse_phase=0;
    spawn_target(*cm,1,1);
}

// ── main ───────────────────────────────────────────────────────────────────
int main(void){
    volatile int *pixel_ctrl=(int*)0xFF203020;

    // Bootstrap double buffer:
    // Buffer1 = initial back (we draw into this first)
    // Buffer2 = initial front (hardware displays this — starts as garbage/black)
    front_buf=Buffer2;
    back_buf =Buffer1;

    // Init hardware to show Buffer2 as front
    *(pixel_ctrl+1)=(int)Buffer2;
    *pixel_ctrl=1;
    while((*(pixel_ctrl+3)&1)!=0);

    int cm=0;
    int px=col_to_px(1), py=row_to_py(1);
    agent_px=col_to_px(2); agent_py=row_to_py(1);
    pulse_phase=0; cam_ox=0; cam_oy=0; osc_phase=0;
    spawn_target(cm,1,1);

    // Draw initial frame and flip
    redraw_all(cm,px,py);
    flip();

    int e0=0,skip=0;
    int agent_tick=0;
    int needs_redraw=0;

    while(1){

        // ── agent tick: move + advance osc + advance pulse ─────────────────
        agent_tick++;
        if(agent_tick >= 80000){
            agent_tick=0;

            // advance pulse ring
            pulse_phase=(pulse_phase+1)&3;

            // advance camera orbit — one step per agent move
            // Using two sinusoids 90° apart gives a smooth elliptical tilt
            osc_phase=(osc_phase+1)&63;
            cam_ox=(sin64[osc_phase]          * TILT_R) / 32;
            cam_oy=(sin64[(osc_phase+16)&63]  * TILT_R) / 32;

            // snap agent to tile, look up Q-table, move
            int ac=px_to_col(agent_px), ar=py_to_row(agent_py);
            agent_px=col_to_px(ac); agent_py=row_to_py(ar);

            int action=qt_best_action(ac,ar,target_col,target_row,cm);
            int nac=ac,nar=ar;
            if     (action==0)nar--;
            else if(action==1)nar++;
            else if(action==2)nac--;
            else if(action==3)nac++;
            if(nac>=0&&nac<COLS&&nar>=0&&nar<ROWS&&maps[cm][nar][nac]==0){
                agent_px=col_to_px(nac); agent_py=row_to_py(nar);
            }

            if(reached_target(agent_px,agent_py))
                reset_round(&cm,&px,&py);

            needs_redraw=1;
        }

        // ── player input ───────────────────────────────────────────────────
        int b;
        while((b=ps2_read())>=0){
            if(skip){skip=0;e0=0;continue;}
            if(b==0xF0){skip=1;continue;}
            if(b==0xE0){e0=1;continue;}

            int nx=px,ny=py;
            if(e0){
                if     (b==0x6B)nx-=SPEED;
                else if(b==0x74)nx+=SPEED;
                else if(b==0x75)ny-=SPEED;
                else if(b==0x72)ny+=SPEED;
                e0=0;
            } else {
                if     (b==0x1D)ny-=SPEED;
                else if(b==0x1B)ny+=SPEED;
                else if(b==0x1C)nx-=SPEED;
                else if(b==0x23)nx+=SPEED;
            }
            if(!hits_wall(cm,nx,ny)){px=nx;py=ny;}
            if(reached_target(px,py))
                reset_round(&cm,&px,&py);
            needs_redraw=1;
        }

        // ── composite and flip once per dirty frame ────────────────────────
        if(needs_redraw){
            needs_redraw=0;
            redraw_all(cm,px,py);
            flip();
        }
    }
    return 0;
}