
#include <stdlib.h>
//#include "q_table.h"   // auto-generated by train.py, contains the trained Q-table
//#include "p_table.h"

// screen and tile constants
#define SCREEN_W   320
#define SCREEN_H   240
#define BLACK      0x0000
#define TILE       20
#define COLS       10
#define ROWS       10
#define NUM_MAPS   10
#define BALL_SIZE  8
#define SPEED      8

// offset to center the 200x200 maze on the 320x240 screen
#define MAP_OFFSET_X  ((SCREEN_W - COLS*TILE) / 2)   // = 60
#define MAP_OFFSET_Y  ((SCREEN_H - ROWS*TILE) / 2)   // = 20

// color definitions
#define WHITE      0xFFFF
#define RED        0xF800
#define GREEN      0x07E0
#define BLUE       0x001F
#define YELLOW     0xFFE0
#define CYAN       0x07FF
#define MAGENTA    0xF81F
#define ORANGE     0xFD20
#define PINK       0xF81F
#define PURPLE     0x8010

#define COL_BG         0x0000   // black background
#define COL_WALL_OUTER 0x4208   // dark gray wall border
#define COL_WALL_CORE  0xFFFF   // white wall face
#define COL_WALL_SHINE 0xAD55   // light blue-gray wall highlight

// player ball — pink/magenta
#define COL_BALL_OUT   0xF81F   // pink outer ring
#define COL_BALL_MID   0xFC1F   // lighter pink mid
#define COL_BALL_IN    0xFFFF   // white core

// RL agent ball — blue
#define COL_AGENT      0x001F   // blue outer
#define COL_AGENT_MID  0x04FF   // lighter blue mid
#define COL_AGENT_IN   0xFFFF   // white core

// target
#define COL_TGT_OUT    0x07FF   // cyan outer
#define COL_TGT_MID    0x07E0   // green mid
#define COL_TGT_IN     0xFFFF   // white center dot
#define COL_TGT_PULSE1 0x03EF   // teal pulse ring  (frame 0)
#define COL_TGT_PULSE2 0xFFE0   // yellow pulse ring (frame 1)

// 3D rendering constants
#define CAMERA_DISTANCE 135
#define HALF_BOX_WIDTH  16

// pixel buffer — 512 wide because DE1-SoC requires power-of-2 row stride
short int Buffer1[240][512];

// global game state
int target_col, target_row;
int agent_px, agent_py;

// pulse animation state — toggles each agent tick to animate the target ring
int pulse_frame = 0;

// maze layouts  1=wall  0=open
int maps[NUM_MAPS][ROWS][COLS] = {
{   // MAP 0: box with inner cross
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 1: zigzag corridors
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,0,1,0,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,0,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,0,1,0,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,1,1,0,1,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 2: ring with holes
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,0,0,0,0,0,1,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 3: chunks
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,0,1,0,1,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,1,1,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,1,1,0,1},
    {1,0,1,1,1,0,0,0,0,1},
    {1,0,0,0,0,0,1,1,0,1},
    {1,0,1,1,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 4: symmetrical
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 5: pillars
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,0,0,1,0,0,1,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,1,0,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 6: heart outline (playable)
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,1,0,0,0,0,0,0,1,1},
    {1,1,1,0,0,0,0,1,1,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 7: spiral
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,1,0,1,0,0,1,0,1},
    {1,0,1,0,1,1,1,1,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,0,0,0,1,1,1,1,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 8: X hollow
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,1,0,0,0,0,0,0,1,1},
    {1,1,0,0,0,0,0,0,1,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 10: Lara
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,0,1,0,0,0,1,0,0,1},
    {1,0,1,0,0,1,0,1,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,0,0,0,1,0,1,0,1},
    {1,0,0,0,0,1,0,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
};

// tile / pixel conversion helpers
int px_to_col(int px) { return (px + BALL_SIZE/2 - MAP_OFFSET_X) / TILE; }
int py_to_row(int py) { return (py + BALL_SIZE/2 - MAP_OFFSET_Y) / TILE; }
int col_to_px(int col) { return MAP_OFFSET_X + col*TILE + (TILE-BALL_SIZE)/2; }
int row_to_py(int row) { return MAP_OFFSET_Y + row*TILE + (TILE-BALL_SIZE)/2; }

// pixel drawing primitives
void plot_pixel(int x, int y, short int color) {
    if (x<0||x>319||y<0||y>239) return;
    Buffer1[y][x] = color;
}

void draw_rect(int x, int y, int w, int h, short int color) {
    for (int r = 0; r < h; r++)
        for (int c = 0; c < w; c++)
            plot_pixel(x+c, y+r, color);
}

void draw_circle(int cx, int cy, int r, short int color) {
    int x = 0, y = r, d = 1 - r;
    while (x <= y) {
        plot_pixel(cx+x,cy+y,color); plot_pixel(cx-x,cy+y,color);
        plot_pixel(cx+x,cy-y,color); plot_pixel(cx-x,cy-y,color);
        plot_pixel(cx+y,cy+x,color); plot_pixel(cx-y,cy+x,color);
        plot_pixel(cx+y,cy-x,color); plot_pixel(cx-y,cy-x,color);
        if (d < 0) d += 2*x+3;
        else { d += 2*(x-y)+5; y--; }
        x++;
    }
}

void fill_circle(int cx, int cy, int r, short int color) {
    for (int dy = -r; dy <= r; dy++)
        for (int dx = -r; dx <= r; dx++)
            if (dx*dx + dy*dy <= r*r)
                plot_pixel(cx+dx, cy+dy, color);
}

int abs(int x) { return x > 0 ? x : -x; }
void swap(int *x, int *y) { int t = *x; *x = *y; *y = t; }

void line(int x0, int y0, int x1, int y1, short color) {
    int steep = abs(y1-y0) > abs(x1-x0);
    if (steep)  { swap(&x0,&y0); swap(&x1,&y1); }
    if (x0>x1)  { swap(&x0,&x1); swap(&y0,&y1); }
    int dx = x1-x0, dy = abs(y1-y0);
    int err = -(dx/2), y = y0, ys = y0<y1 ? 1 : -1;
    for (int i = x0; i <= x1; i++) {
        if (steep) plot_pixel(y,i,color); else plot_pixel(i,y,color);
        err += dy;
        if (err > 0) { y += ys; err -= dx; }
    }
}

// scanline-fill a convex quad
// uses two slightly different fill modes to handle quads above/below screen center
void quad(int x0, int y0, int x1, int y1,
          int x2, int y2, int x3, int y3, short color) {
    int xs[4] = {x0,x1,x2,x3};
    int ys[4] = {y0,y1,y2,y3};

    int ymin = ys[0], ymax = ys[0];
    for (int i = 1; i < 4; i++) {
        if (ys[i] < ymin) ymin = ys[i];
        if (ys[i] > ymax) ymax = ys[i];
    }

    if (((x0>160)&&(y0>120)) || ((x0<160)&&(y0<120))) {
        // fill interior (exclusive top edge)
        for (int y = ymin+1; y < ymax; y++) {
            int intersections[4]; int count = 0;
            for (int i = 0; i < 4; i++) {
                int ax=xs[i], ay=ys[i], bx=xs[(i+1)%4], by=ys[(i+1)%4];
                if ((y>ay&&y<=by)||(y>by&&y<=ay)) {
                    intersections[count++] = ax + (y-ay)*(bx-ax)/(by-ay);
                }
            }
            for (int a = 0; a < count-1; a++)
                for (int b = a+1; b < count; b++)
                    if (intersections[a]>intersections[b]) {
                        int tmp=intersections[a];
                        intersections[a]=intersections[b];
                        intersections[b]=tmp;
                    }
            for (int a = 0; a < count-1; a += 2)
                for (int x = intersections[a]+1; x < intersections[a+1]; x++)
                    plot_pixel(x, y, color);
        }
    } else {
        // fill interior (inclusive edges)
        for (int y = ymin; y <= ymax; y++) {
            int intersections[4]; int count = 0;
            for (int i = 0; i < 4; i++) {
                int ax=xs[i], ay=ys[i], bx=xs[(i+1)%4], by=ys[(i+1)%4];
                if ((y>ay&&y<=by)||(y>by&&y<=ay)) {
                    intersections[count++] = ax + (y-ay)*(bx-ax)/(by-ay);
                }
            }
            for (int a = 0; a < count-1; a++)
                for (int b = a+1; b < count; b++)
                    if (intersections[a]>intersections[b]) {
                        int tmp=intersections[a];
                        intersections[a]=intersections[b];
                        intersections[b]=tmp;
                    }
            for (int a = 0; a < count-1; a += 2)
                for (int x = intersections[a]; x <= intersections[a+1]; x++)
                    plot_pixel(x, y, color);
        }
    }
}

// Pixel Art

void plot_black_white(int* matrix, int rows, int cols, int xOffset, int yOffset, int pixelSize) {
	short curr_col; 
	int draw_x;
	int draw_y;
	for(int x = 0; x < cols; x++){
        for(int y = 0; y < rows; y++){
			if (matrix[y * cols + x]) {curr_col = WHITE;}
			else {curr_col = BLACK;}
            
			for(int dy = 0; dy < pixelSize; dy++){
                for(int sx = 0; sx < pixelSize; sx++){
					
					draw_x = x * pixelSize + sx + xOffset;
					draw_y = y * pixelSize + dy + yOffset;
                    plot_pixel(draw_x, draw_y, curr_col);
                }
            }
        }
    }
}

#define LOGO_PX_SIZE 1
#define LOGO_X 280
#define LOGO_Y 195
	
int logo[28][34] = {
	{0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0},
	{0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,1,1,0,0,0,0,0,0},
	{0,1,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,1,1,0,0,0,0,0,0},
	{0,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0},
	{0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0},
	{0,1,1,0,1,1,1,0,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0},
	{0,1,1,0,0,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,1,1,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0},
	{0,1,1,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0},
	{0,1,1,0,0,0,0,0,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,1,1,1,1,1,0},
	{0,1,1,0,0,0,0,0,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,1,1,1,0,0,1,1,1,1,1,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,1,1,1,0,0,0,1,1,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,1,1,1,0,0,0,0,1,1,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,1,0,0,0,0,0,1,1,1,1,1,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,1,1,1,1,1,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,1,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,1,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0},
};


void plot_logo() {
	plot_black_white(logo, 28, 34, LOGO_X, LOGO_Y, LOGO_PX_SIZE);
}

// 3D perspective projection
struct TwoDPoint { int x; int y; };
struct BoxPoints {
    struct TwoDPoint ftl,ftr,fbl,fbr,btl,btr,bbl,bbr;
};

struct TwoDPoint projectPoint(int x, int y, int z) {
    struct TwoDPoint p;
    int d = CAMERA_DISTANCE;
    p.x = (-(x)*d)/(z-d)+160;
    p.y = (-(y)*d)/(z-d)+120;
    return p;
}

struct BoxPoints getBoxPoints(int x, int y, int z) {
    struct BoxPoints b; int w = HALF_BOX_WIDTH;
    b.ftl=projectPoint(x-w,y+w,z+w); b.ftr=projectPoint(x+w,y+w,z+w);
    b.fbl=projectPoint(x-w,y-w,z+w); b.fbr=projectPoint(x+w,y-w,z+w);
    b.btl=projectPoint(x-w,y+w,z-w); b.btr=projectPoint(x+w,y+w,z-w);
    b.bbl=projectPoint(x-w,y-w,z-w); b.bbr=projectPoint(x+w,y-w,z-w);
    return b;
}

// draw a 3D box with colored side faces and a white top face
void drawBox(int x, int y, int z, short color) {
    struct BoxPoints box = getBoxPoints(x,y,z);

    // colored side faces — only draw the face visible from camera position
    if (y<0)
        quad(box.btl.x,box.btl.y, box.btr.x,box.btr.y,
             box.ftr.x,box.ftr.y, box.ftl.x,box.ftl.y, RED);
    if (x>0)
        quad(box.fbl.x,box.fbl.y, box.bbl.x,box.bbl.y,
             box.btl.x,box.btl.y, box.ftl.x,box.ftl.y, GREEN);
    if (x<0)
        quad(box.ftr.x,box.ftr.y, box.btr.x,box.btr.y,
             box.bbr.x,box.bbr.y, box.fbr.x,box.fbr.y, BLUE);
    if (y>0)
        quad(box.fbl.x,box.fbl.y, box.fbr.x,box.fbr.y,
             box.bbr.x,box.bbr.y, box.bbl.x,box.bbl.y, ORANGE);

    // top/front face — always white
    quad(box.ftl.x,box.ftl.y, box.ftr.x,box.ftr.y,
         box.fbr.x,box.fbr.y, box.fbl.x,box.fbl.y, COL_WALL_CORE);

    // front face wireframe outline
    line(box.ftl.x,box.ftl.y, box.ftr.x,box.ftr.y, color);
    line(box.ftr.x,box.ftr.y, box.fbr.x,box.fbr.y, color);
    line(box.fbr.x,box.fbr.y, box.fbl.x,box.fbl.y, color);
    line(box.fbl.x,box.fbl.y, box.ftl.x,box.ftl.y, color);

    // back edges — only draw visible ones
    if(y<0) line(box.btl.x,box.btl.y, box.btr.x,box.btr.y, color);
    if(x<0) line(box.btr.x,box.btr.y, box.bbr.x,box.bbr.y, color);
    if(y>0) line(box.bbr.x,box.bbr.y, box.bbl.x,box.bbl.y, color);
    if(x>0) line(box.bbl.x,box.bbl.y, box.btl.x,box.btl.y, color);

    // connecting edges front-to-back
    if((y<0)||(x>0)) line(box.ftl.x,box.ftl.y, box.btl.x,box.btl.y, color);
    if((y<0)||(x<0)) line(box.ftr.x,box.ftr.y, box.btr.x,box.btr.y, color);
    if((y>0)||(x>0)) line(box.fbl.x,box.fbl.y, box.bbl.x,box.bbl.y, color);
    if((y>0)||(x<0)) line(box.fbr.x,box.fbr.y, box.bbr.x,box.bbr.y, color);
}

// draw one wall tile as a 3D box at the given tile position
#define TILT_OFFSET 10
#define BASE_DISTANCE -250
char prev_tilt = 'n';
	
void draw_wall_tile(int col, int row, char tilt) {
    int x = col*3*TILE-260;
    int y = row*3*TILE-270;
	int htilt=0;
	int vtilt=0;
	
	if (tilt == 'l') htilt=1; //left
	if (tilt == 'r') htilt=-1; //right
	if (tilt == 'u') vtilt=1; //up
	if (tilt == 'd') vtilt=-1; //down
	if (tilt == 'n') {} //no button clicked

	int z = BASE_DISTANCE + ((x*htilt)/TILT_OFFSET) + ((y*vtilt)/TILT_OFFSET);
	
    drawBox(x, y, z, 0x9534);
}

// sprite drawing

// draw the player ball (PINK) or RL agent ball (BLUE)
// pass color==BLACK to erase (draws a black rectangle over the bounding box)
void draw_ball(int x, int y, short int color) {
    int cx = x + BALL_SIZE/2;
    int cy = y + BALL_SIZE/2;

    if (color == BLACK) {
        draw_rect(x-1, y-1, BALL_SIZE+2, BALL_SIZE+2, BLACK);
        return;
    }

    // single solid ball
    short int base = (color == COL_AGENT) ? COL_AGENT : COL_BALL_OUT;
    fill_circle(cx, cy, BALL_SIZE/2, base);

    // off-center white highlight (gives 3D look)
    plot_pixel(cx-1, cy-2, WHITE);
    plot_pixel(cx-2, cy-2, WHITE);
}

// draw the target at tile (col, row)
void draw_target(int col, int row, short int color) {
    int px = col_to_px(col);
    int py = row_to_py(row);

    int cx = px + BALL_SIZE/2;
    int cy = py + BALL_SIZE/2;

    if (color == BLACK) {
        draw_rect(px-1, py-1, BALL_SIZE+2, BALL_SIZE+2, BLACK);
        return;
    }

    // pulse ring
    int r_outer = (pulse_frame == 0) ? 7 : 8;
    draw_circle(cx, cy, r_outer, COL_TGT_OUT);

    // main turquoise
    fill_circle(cx, cy, BALL_SIZE/2, COL_TGT_OUT);

    // white center dot
    plot_pixel(cx, cy, WHITE);
    plot_pixel(cx+1, cy, WHITE);
    plot_pixel(cx, cy+1, WHITE);
    plot_pixel(cx+1, cy+1, WHITE);
}

// clear screen and redraw all wall tiles for map m
void draw_map(int m, char tilt) {
    for (int y = 0; y < SCREEN_H; y++)
        for (int x = 0; x < SCREEN_W; x++)
            Buffer1[y][x] = BLACK;
    for (int row = 0; row < ROWS; row++)
        for (int col = 0; col < COLS; col++)
            if (maps[m][row][col] == 1)
                draw_wall_tile(col, row, tilt);
	plot_logo();

}

// pick a random open tile for the target, avoiding the ball start tile (bc, br)
void spawn_target(int m, int bc, int br) {
    int col, row;
    do {
        col = 1 + rand() % (COLS-2);
        row = 1 + rand() % (ROWS-2);
    } while (maps[m][row][col] != 0 || (col==bc && row==br));
    target_col = col;
    target_row = row;
    draw_target(target_col, target_row, COL_TGT_OUT);
}

// collision / detection

// check all 4 corners of the 8x8 ball bounding box for wall overlap
int hits_wall(int m, int px, int py) {
    int pts[4][2] = {
        {px,py}, {px+BALL_SIZE-1,py},
        {px,py+BALL_SIZE-1}, {px+BALL_SIZE-1,py+BALL_SIZE-1}
    };
    for (int i = 0; i < 4; i++) {
        int col = (pts[i][0]-MAP_OFFSET_X)/TILE;
        int row = (pts[i][1]-MAP_OFFSET_Y)/TILE;
        if (col<0||col>=COLS||row<0||row>=ROWS) return 1;
        if (maps[m][row][col]==1) return 1;
    }
    return 0;
}

// check if ball center tile matches the target tile
int reached_target(int px, int py) {
    int bc = (px+BALL_SIZE/2-MAP_OFFSET_X)/TILE;
    int br = (py+BALL_SIZE/2-MAP_OFFSET_Y)/TILE;
    return (bc==target_col && br==target_row);
}

// hardware I/O
void wait_for_vsync(void) {
    volatile int *ctrl = (int *)0xFF203020;
    *ctrl = 1;
    while ((*(ctrl+3) & 0x01) != 0);
}

volatile int *ps2 = (volatile int *)0xFF200100;
int ps2_read() {
    int val = *ps2;
    if (val & 0x8000) return val & 0xFF;
    return -1;
}

// round reset — pick new map, place both balls, spawn target
void reset_round(int *cm, int *px, int *py) {
    *cm = rand() % NUM_MAPS;
    draw_map(*cm, 'n');
    *px     = col_to_px(1);
    *py     = row_to_py(1);
    agent_px = col_to_px(2);
    agent_py = row_to_py(1);
    pulse_frame = 0;
    draw_ball(*px, *py, COL_BALL_OUT);
    draw_ball(agent_px, agent_py, COL_AGENT);
    spawn_target(*cm, 1, 1);
	prev_tilt = 'u';

}

// main game loop

int main(void) {
    volatile int *pixel_ctrl = (int *)0xFF203020;
    *(pixel_ctrl+1) = (int)&Buffer1;
    *pixel_ctrl = 1;
    while ((*(pixel_ctrl+3) & 0x01) != 0);
    *(pixel_ctrl+1) = (int)&Buffer1;

    int cm = 0; // Current map, start at first then be random
    draw_map(cm, 0);

    // player starts at tile (1,1)
    int px = col_to_px(1);
    int py = row_to_py(1);
    draw_ball(px, py, COL_BALL_OUT);

    // RL agent starts at tile (2,1), one tile right of player
    agent_px = col_to_px(2);
    agent_py = row_to_py(1);
    draw_ball(agent_px, agent_py, COL_AGENT);

    spawn_target(cm, 1, 1); // Spawns in a non taken space

    int e0 = 0, skip = 0; //for ps2 keyboard
    int agent_tick = 0; //how fast to update RL model (speed)

    while (1) {

        // RL AGENT MOVEMENT
        agent_tick++;
        if (agent_tick >= 100000) { //Don't draw and update too frequent
            agent_tick = 0; //reset count

            // get agent's current tile
            int ac = px_to_col(agent_px);
            int ar = py_to_row(agent_py);

            // snap to exact tile center to prevent floating-point-style pixel drift
            agent_px = col_to_px(ac);
            agent_py = row_to_py(ar);

            // Q-table lookup: best action for (current tile, target tile, map)
            int action = qt_best_action(ac, ar, target_col, target_row, cm);

            int nac = ac, nar = ar;
            if (action == 0) nar -= 1;   // up
            else if (action == 1) nar += 1;   // down
            else if (action == 2) nac -= 1;   // left
            else if (action == 3) nac += 1;   // right

            //check bounds
            if (nac >= 0 && nac < COLS && nar >= 0 && nar < ROWS
                    && maps[cm][nar][nac] == 0) {
        
                draw_ball(agent_px, agent_py, BLACK);  // erase old position
                agent_px = col_to_px(nac); //update postiion
                agent_py = row_to_py(nar);
                draw_target(target_col, target_row, COL_TGT_OUT);  // redraw target underneath
                draw_ball(agent_px, agent_py, COL_AGENT);     // draw new position
            }

            if (reached_target(agent_px, agent_py)) {
                reset_round(&cm, &px, &py);
                agent_tick = 0;
                continue;
            }
        }

        // PLAYER KEYBOARD INPUT 
        // PS2 protocol: 0xF0 = key release prefix, 0xE0 = extended key prefix
        int b;
		
        while ((b = ps2_read()) >= 0) {
            if (skip) { skip=0; e0=0; continue; }   // discard key-release scan code
            if (b == 0xF0) { skip=1; continue; }    // next byte is a key release
            if (b == 0xE0) { e0=1;   continue; }    // next byte is extended key

            int nx = px, ny = py;
            if (e0) {
                if (b==0x6B) { // left arrow
					nx -= SPEED;
					if (prev_tilt != 'l') draw_map(cm, 'l');
					prev_tilt = 'l';
				} 
				
                else if (b==0x74) {// right arrow
					nx += SPEED;   
					if (prev_tilt != 'r') draw_map(cm, 'r');
					prev_tilt = 'r';
				}
                else if (b==0x75) {// up arrow
					ny -= SPEED;
					if (prev_tilt != 'u') draw_map(cm, 'u');
					prev_tilt = 'u';
				}
                else if (b==0x72) {// down arrow
					ny += SPEED;
					if (prev_tilt != 'd') draw_map(cm, 'd');
					prev_tilt = 'd';
				}
                e0 = 0;
            } else {
                if (b==0x1D) { // W
					ny -= SPEED;
					if (prev_tilt != 'u') draw_map(cm, 'u');
					prev_tilt = 'u';
				} 
                else if (b==0x1B) { // S
					ny += SPEED;   
					if (prev_tilt != 'd') draw_map(cm, 'd');
					prev_tilt = 'd';
				}  
                else if (b==0x1C) {//A
					nx -= SPEED;
					if (prev_tilt != 'l') draw_map(cm, 'l');
					prev_tilt = 'l';
				}
                else if (b==0x23) {//D
					nx += SPEED;
					if (prev_tilt != 'r') draw_map(cm, 'r');
					prev_tilt = 'r';
				} 
            } 
			
			 draw_ball(px, py, COL_BALL_OUT);                   // redraw player
			
			
            if (!hits_wall(cm, nx, ny)) {
                
                draw_ball(px, py, BLACK);                          // erase player
                px = nx; 
                py = ny;
                draw_target(target_col, target_row, COL_TGT_OUT); // redraw target
                draw_ball(agent_px, agent_py, COL_AGENT);          // redraw agent
                draw_ball(px, py, COL_BALL_OUT);                   // draw player
            }

            if (reached_target(px, py)) {
                reset_round(&cm, &px, &py);
                agent_tick = 0;
            }
        }
    }
    return 0;
}