// ball.c

// Main game file for the FPGA maze.
// Two balls navigate the maze:
//   RED ball  — controlled by the player via PS2 keyboard
//   GREEN ball — controlled by the trained RL agent via q_table.h
//
// The RL agent works by calling qt_best_action() every 80000 loop ticks.
// It looks up the Q-table (baked in from q_table.h) to decide which direction
// to move. No Python, no serial, no communication needed at runtime.

#include <stdlib.h>
#include "q_table.h"   // auto-generated by train.py, contains the trained Q-table

// screen and tile constants 
#define SCREEN_W   320
#define SCREEN_H   240
#define BLACK      0x0000
#define TILE       20    // each maze tile is 20x20 pixels
#define COLS       10    // maze is 10 tiles wide
#define ROWS       10    // maze is 10 tiles tall
#define NUM_MAPS   6     // 6 different maze layouts
#define BALL_SIZE  8     // ball sprite is 8x8 pixels
#define SPEED      8     // player moves 8 pixels per keypress (= 1 tile)

// offset to center the 200x200 maze on the 320x240 screen
#define MAP_OFFSET_X  ((SCREEN_W - COLS*TILE) / 2)   // = 60
#define MAP_OFFSET_Y  ((SCREEN_H - ROWS*TILE) / 2)   // = 20

// color definitions 
#define COL_BG         0x0000   // black background
#define COL_WALL_OUTER 0x4208   // dark gray wall border
#define COL_WALL_CORE  0xFFFF   // white wall center
#define COL_WALL_SHINE 0xAD55   // light blue-gray wall highlight
#define COL_BALL_OUT   0xF800   // red outer ring  (player ball)
#define COL_BALL_MID   0xFC10   // orange mid ring (player ball)
#define COL_BALL_IN    0xFFF0   // yellow core     (player ball)
#define COL_TGT_OUT    0x07FF   // cyan outer ring  (target)
#define COL_TGT_MID    0x07E0   // green mid ring   (target)
#define COL_TGT_IN     0xFFFF   // white center dot (target)
#define COL_TGT_PULSE  0x03EF   // teal pulse ring  (target)
#define COL_AGENT      0x07E0   // green agent ball (RL agent)

// pixel buffer
// Buffer1[y][x] = color value for pixel at (x,y)
// 512 wide (not 320) because the DE1-SoC hardware requires power-of-2 row width
short int Buffer1[240][512];

// global game state
int target_col, target_row;   // current target tile position
int agent_px, agent_py;       // RL agent pixel position

// the 6 maze layouts 1=wall, 0=open
// The RL agent was trained on these exact layouts
int maps[NUM_MAPS][ROWS][COLS] = {
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,0,1,0,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,0,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,0,1,0,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,1,1,0,1,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,0,0,0,0,0,1,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,0,1,0,1,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,1,1,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,1,1,0,1},
    {1,0,1,1,1,0,0,0,0,1},
    {1,0,0,0,0,0,1,1,0,1},
    {1,0,1,1,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,0,0,1,0,0,1,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,1,0,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
};

// tile/pixel conversion helpers
// The RL agent works in TILE coordinates (0-9)
// The display works in PIXEL coordinates (0-319, 0-239)
// These functions convert between them

// pixel position -> which tile column is the center of this ball in?
int px_to_col(int px) { return (px + BALL_SIZE/2 - MAP_OFFSET_X) / TILE; }

// pixel position -> which tile row?
int py_to_row(int py) { return (py + BALL_SIZE/2 - MAP_OFFSET_Y) / TILE; }

// tile column -> pixel x of top-left corner of ball in that tile
int col_to_px(int col) { return MAP_OFFSET_X + col*TILE + (TILE-BALL_SIZE)/2; }

// tile row -> pixel y of top-left corner of ball in that tile
int row_to_py(int row) { return MAP_OFFSET_Y + row*TILE + (TILE-BALL_SIZE)/2; }


// pixel drawing functions

// plot a single pixel to the buffer
void plot_pixel(int x, int y, short int color) {
    if(x<0||x>319||y<0||y>239) return;   // bounds check
    Buffer1[y][x] = color;
}

// draw a filled rectangle
void draw_rect(int x, int y, int w, int h, short int color) {
    for (int r = 0; r < h; r++)
        for (int c = 0; c < w; c++)
            plot_pixel(x+c, y+r, color);
}

// draw a circle outline using Bresenham's circle algorithm
void draw_circle(int cx, int cy, int r, short int color) {
    int x = 0, y = r, d = 1 - r;
    while (x <= y) {
        // plot 8 symmetric points around the circle
        plot_pixel(cx+x,cy+y,color); plot_pixel(cx-x,cy+y,color);
        plot_pixel(cx+x,cy-y,color); plot_pixel(cx-x,cy-y,color);
        plot_pixel(cx+y,cy+x,color); plot_pixel(cx-y,cy+x,color);
        plot_pixel(cx+y,cy-x,color); plot_pixel(cx-y,cy-x,color);
        if (d < 0) d += 2*x+3;
        else { d += 2*(x-y)+5; y--; }
        x++;
    }
}

// draw a filled circle
void fill_circle(int cx, int cy, int r, short int color) {
    for (int dy = -r; dy <= r; dy++)
        for (int dx = -r; dx <= r; dx++)
            if (dx*dx + dy*dy <= r*r)
                plot_pixel(cx+dx, cy+dy, color);
}

int abs(int x) { return x > 0 ? x : -x; }
void swap(int *x, int *y) { int t = *x; *x = *y; *y = t; }

// draw a line using Bresenham's line algorithm
void line(int x0, int y0, int x1, int y1, short color) {
    int steep = abs(y1-y0) > abs(x1-x0);
    if (steep)  { swap(&x0,&y0); swap(&x1,&y1); }
    if (x0>x1)  { swap(&x0,&x1); swap(&y0,&y1); }
    int dx = x1-x0, dy = abs(y1-y0);
    int err = -(dx/2), y = y0, ys = y0<y1 ? 1 : -1;
    for (int i = x0; i <= x1; i++) {
        if (steep) plot_pixel(y,i,color); else plot_pixel(i,y,color);
        err += dy;
        if (err > 0) { y += ys; err -= dx; }
    }
}

// 3D wall rendering 
// The walls are drawn as 3D boxes using perspective projection

#define CAMERA_DISTANCE 135   // virtual camera distance for perspective
#define HALF_BOX_WIDTH  16    // half the width of each 3D box

struct TwoDPoint { int x; int y; };
struct BoxPoints {
    // 8 corners of a 3D box projected to 2D screen coordinates
    // f=front, b=back, t=top, b=bottom, l=left, r=right
    struct TwoDPoint ftl,ftr,fbl,fbr,btl,btr,bbl,bbr;
};

// project a 3D point (x,y,z) to 2D screen using perspective division
struct TwoDPoint projectPoint(int x, int y, int z) {
    struct TwoDPoint p;
    int d = CAMERA_DISTANCE;
    p.x = (-(x)*d)/(z-d)+160;   // 160 = screen center x
    p.y = (-(y)*d)/(z-d)+120;   // 120 = screen center y
    return p;
}

// get all 8 projected corners of a box at position (x,y,z)
struct BoxPoints getBoxPoints(int x, int y, int z) {
    struct BoxPoints b; int w = HALF_BOX_WIDTH;
    b.ftl=projectPoint(x-w,y+w,z+w); b.ftr=projectPoint(x+w,y+w,z+w);
    b.fbl=projectPoint(x-w,y-w,z+w); b.fbr=projectPoint(x+w,y-w,z+w);
    b.btl=projectPoint(x-w,y+w,z-w); b.btr=projectPoint(x+w,y+w,z-w);
    b.bbl=projectPoint(x-w,y-w,z-w); b.bbr=projectPoint(x+w,y-w,z-w);
    return b;
}

// draw a 3D wireframe box, only draws visible faces based on position
void drawBox(int x, int y, int z, short color) {
    struct BoxPoints b = getBoxPoints(x,y,z);
    // front face, always visible
    line(b.ftl.x,b.ftl.y,b.ftr.x,b.ftr.y,color);
    line(b.ftr.x,b.ftr.y,b.fbr.x,b.fbr.y,color);
    line(b.fbr.x,b.fbr.y,b.fbl.x,b.fbl.y,color);
    line(b.fbl.x,b.fbl.y,b.ftl.x,b.ftl.y,color);

    // back and side face only drawn when facing camera
    if(y<0) line(b.btl.x,b.btl.y,b.btr.x,b.btr.y,color);
    if(x<0) line(b.btr.x,b.btr.y,b.bbr.x,b.bbr.y,color);
    if(y>0) line(b.bbr.x,b.bbr.y,b.bbl.x,b.bbl.y,color);
    if(x>0) line(b.bbl.x,b.bbl.y,b.btl.x,b.btl.y,color);

    if((y<0)||(x>0)) line(b.ftl.x,b.ftl.y,b.btl.x,b.btl.y,color);
    if((y<0)||(x<0)) line(b.ftr.x,b.ftr.y,b.btr.x,b.btr.y,color);
    if((y>0)||(x>0)) line(b.fbl.x,b.fbl.y,b.bbl.x,b.bbl.y,color);
    if((y>0)||(x<0)) line(b.fbr.x,b.fbr.y,b.bbr.x,b.bbr.y,color);
}

// draw one wall tile as a 3D box at the given tile position
void draw_wall_tile(int col, int row) {
    // convert tile coords to 3D world coords
    int x = col*3*TILE-260, y = row*3*TILE-270;
    drawBox(x, y, -250, 0x9534);
}

// draw a layered ball — 3 concentric circles for a shiny look
// if color==BLACK, just erase the ball area
void draw_ball(int x, int y, short int color) {
    int cx = x + BALL_SIZE/2;   // center of ball
    int cy = y + BALL_SIZE/2;
    if (color == BLACK) {
        // erase by drawing a black rectangle over the ball area
        draw_rect(x-1, y-1, BALL_SIZE+2, BALL_SIZE+2, BLACK);
        return;
    }
    // outer ring — red for player, green for agent
    fill_circle(cx, cy, BALL_SIZE/2,     color == COL_AGENT ? COL_AGENT : COL_BALL_OUT);
    // mid ring — darker shade
    fill_circle(cx, cy, BALL_SIZE/2 - 2, color == COL_AGENT ? 0x0410   : COL_BALL_MID);
    // bright core
    fill_circle(cx, cy, BALL_SIZE/2 - 3, color == COL_AGENT ? 0xFFFF   : COL_BALL_IN);
    // specular highlight dot for glossy effect
    plot_pixel(cx-1, cy-2, 0xFFFF);
}

// draw the target marker — layered circles with a white center dot
void draw_target(int col, int row, short int color) {
    int cx = MAP_OFFSET_X + col*TILE + TILE/2;
    int cy = MAP_OFFSET_Y + row*TILE + TILE/2;
    if (color == BLACK) {
        draw_rect(cx-TILE/2, cy-TILE/2, TILE, TILE, BLACK);
        return;
    }
    draw_circle(cx, cy, 6, COL_TGT_PULSE);   // outer pulse ring
    fill_circle(cx, cy, 4, COL_TGT_OUT);      // cyan fill
    fill_circle(cx, cy, 2, COL_TGT_MID);      // green mid
    plot_pixel(cx,   cy,   COL_TGT_IN);        // white center
    plot_pixel(cx+1, cy,   COL_TGT_IN);
    plot_pixel(cx,   cy+1, COL_TGT_IN);
    plot_pixel(cx+1, cy+1, COL_TGT_IN);
}

// clear screen and redraw all wall tiles for map m
void draw_map(int m) {
    for (int y = 0; y < SCREEN_H; y++)
        for (int x = 0; x < SCREEN_W; x++)
            Buffer1[y][x] = BLACK;
    for (int row = 0; row < ROWS; row++)
        for (int col = 0; col < COLS; col++)
            if (maps[m][row][col] == 1)
                draw_wall_tile(col, row);
}

// pick a random open tile for the target (not the same as start tile)
void spawn_target(int m, int bc, int br) {
    int col, row;
    do {
        col = 1 + rand() % (COLS-2);
        row = 1 + rand() % (ROWS-2);
    } while (maps[m][row][col] != 0 || (col==bc && row==br));
    target_col = col; target_row = row;
    draw_target(target_col, target_row, COL_TGT_OUT);
}

// check if ball at pixel position (px,py) would overlap a wall
// checks all 4 corners of the 8x8 ball bounding box
int hits_wall(int m, int px, int py) {
    int pts[4][2] = {
        {px,py},{px+BALL_SIZE-1,py},
        {px,py+BALL_SIZE-1},{px+BALL_SIZE-1,py+BALL_SIZE-1}
    };
    for (int i = 0; i < 4; i++) {
        int col = (pts[i][0]-MAP_OFFSET_X)/TILE;
        int row = (pts[i][1]-MAP_OFFSET_Y)/TILE;
        if (col<0||col>=COLS||row<0||row>=ROWS) return 1;
        if (maps[m][row][col]==1) return 1;
    }
    return 0;
}

// check if ball at (px,py) is in the same tile as the target
int reached_target(int px, int py) {
    int bc = (px+BALL_SIZE/2-MAP_OFFSET_X)/TILE;
    int br = (py+BALL_SIZE/2-MAP_OFFSET_Y)/TILE;
    return (bc==target_col && br==target_row);
}

// wait for VGA vertical sync to prevent screen tearing
void wait_for_vsync(void) {
    volatile int *ctrl = (int *)0xFF203020;
    *ctrl = 1;
    while ((*(ctrl+3) & 0x01) != 0);
}

// read one byte from the PS2 keyboard
// returns -1 if no key data available
volatile int *ps2 = (volatile int *)0xFF200100;
int ps2_read() {
    int val = *ps2;
    if (val & 0x8000) return val & 0xFF;
    return -1;
}

// reset, called when either ball reaches the target
void reset_round(int *cm, int *px, int *py) {
    *cm = rand() % NUM_MAPS;        // pick a random new map
    draw_map(*cm);                   // draw it
    *px = col_to_px(1);             // reset player to tile (1,1)
    *py = row_to_py(1);
    agent_px = col_to_px(2);        // reset agent to tile (2,1)
    agent_py = row_to_py(1);
    draw_ball(*px, *py, COL_BALL_OUT);
    draw_ball(agent_px, agent_py, COL_AGENT);
    spawn_target(*cm, 1, 1);        // spawn new random target
}

// main — game loop
int main(void) {
    volatile int *pixel_ctrl = (int *)0xFF203020;
    *(pixel_ctrl+1) = (int)&Buffer1;
    *pixel_ctrl = 1;
    while ((*(pixel_ctrl+3) & 0x01) != 0);
    *(pixel_ctrl+1) = (int)&Buffer1;

    int cm = 0; // current map index
    draw_map(cm);

    // player starts at tile (1,1)
    int px = col_to_px(1);
    int py = row_to_py(1);
    draw_ball(px, py, COL_BALL_OUT);

    // RL agent starts at tile (2,1) — one tile right of player
    agent_px = col_to_px(2);
    agent_py = row_to_py(1);
    draw_ball(agent_px, agent_py, COL_AGENT);

    spawn_target(cm, 1, 1);

    int e0 = 0, skip = 0;   // PS2 keyboard state machine variables
    int agent_tick = 0;     // counter to slow the agent down to a visible speed

    while (1) {

        // RL AGENT MOVEMENT 
        // The agent moves every 80000 loop iterations — roughly human speed
        // Without this delay it would move thousands of times per second
        agent_tick++;
        if (agent_tick >= 800000) {
            agent_tick = 0;

            // get agent's current tile position
            int ac = px_to_col(agent_px);
            int ar = py_to_row(agent_py);

            // snap to exact tile to prevent pixel drift accumulating
            // (small rounding errors could cause wrong tile lookups over time)
            agent_px = col_to_px(ac);
            agent_py = row_to_py(ar);

            // ask the Q-table: given current tile and target tile, what's best?
            // this is a single array lookup — very fast on the FPGA
            int action = qt_best_action(ac, ar, target_col, target_row, cm);

            // convert action to next tile position
            int nac = ac, nar = ar;
            if      (action == 0) nar -= 1;   // up
            else if (action == 1) nar += 1;   // down
            else if (action == 2) nac -= 1;   // left
            else if (action == 3) nac += 1;   // right

            // only move if destination tile is valid and not a wall
            if (nac >= 0 && nac < COLS && nar >= 0 && nar < ROWS
                    && maps[cm][nar][nac] == 0) {
                draw_ball(agent_px, agent_py, BLACK);      // erase old position
                agent_px = col_to_px(nac);
                agent_py = row_to_py(nar);
                draw_target(target_col, target_row, COL_TGT_OUT);  // redraw target
                draw_ball(agent_px, agent_py, COL_AGENT);  // draw new position
            }

            // check if agent reached the target
            if (reached_target(agent_px, agent_py)) {
                reset_round(&cm, &px, &py);
                agent_tick = 0;
                continue;
            }
        }

        // PLAYER KEYBOARD INPUT
        // PS2 sends scan codes. Key releases send 0xF0 followed by the key code.
        // Extended keys (arrow keys) send 0xE0 followed by the key code.
        int b;
        while ((b = ps2_read()) >= 0) {
            if (skip) { skip=0; e0=0; continue; }    // skip key-release scan code
            if (b == 0xF0) { skip=1; continue; }     // next byte is a key release
            if (b == 0xE0) { e0=1; continue; }       // next byte is extended key

            int nx = px, ny = py;
            if (e0) {
                // arrow keys
                if (b==0x6B) nx -= SPEED;   // left arrow
                else if (b==0x74) nx += SPEED;   // right arrow
                else if (b==0x75) ny -= SPEED;   // up arrow
                else if (b==0x72) ny += SPEED;   // down arrow
                e0 = 0;
            } else {
                // WASD keys
                if (b==0x1D) ny -= SPEED;   // W
                else if (b==0x1B) ny += SPEED;   // S
                else if (b==0x1C) nx -= SPEED;   // A
                else if (b==0x23) nx += SPEED;   // D
            }

            // only move if the new position doesn't overlap a wall
            if (!hits_wall(cm, nx, ny)) {
                draw_ball(px, py, BLACK); // erase old position
                px = nx; py = ny;
                
                draw_target(target_col, target_row, COL_TGT_OUT);  // redraw target
                draw_ball(agent_px, agent_py, COL_AGENT);           // redraw agent
                draw_ball(px, py, COL_BALL_OUT);   // draw player at new position
            }

            // check if player reached the target
            if (reached_target(px, py)) {
                reset_round(&cm, &px, &py);
                agent_tick = 0;
            }
        }
    }
    return 0;
}